In [23]:
from pathlib import Path

folder = Path("/scratch/yag1/ego4d_data/v2/clips")

subdirs = [p.name for p in folder.iterdir() if p.is_dir()]
print(subdirs)

['15b03b30-201b-452b-948a-07571e4177c5', 'ba5b8b24-2335-40c0-86c9-bfd76620e1fa', 'cc2a687e-e871-4319-85c9-c0161678903d', '740a9d13-cf77-4e7d-91b5-a3ebf6d270ec', '3ef4d3b5-2a79-42f0-9609-509f886e7f93', '93df179b-2bde-44e2-b0ea-e9c2c046dd3e', '1731de62-b1b9-4b84-bd55-412cd67e9b3c', 'b8e9a0cb-8a5d-467e-9ff0-873bdfa51037', 'f4c804be-6a83-4f29-9e45-81bf6a2b00cb', 'f9fc7c0a-c42c-4c4c-a4ed-08f078ed5967', '780f7a41-3573-4dd6-8658-d1c8c02ef0ba', '54b5b878-d205-4a16-b945-62a7b08b577c', 'b352dc19-c601-4740-9559-6db99ea782e9', '1c433d54-a8fa-48ec-8fdf-1f8207e7ab38', '3803f332-0ac4-4f11-92c7-319318859908', 'fdb6c695-0a20-4c3d-b81c-80b0f9ec5187', 'd363833d-8f57-4a26-8b09-a1a4675c78c8', 'bf629cf7-b95b-46db-b9b4-93a472057263', 'a325ce85-cae5-4faa-99bb-7272918fcf19', 'f15dbeca-63e7-43b5-b1a6-7896bc28b08c', '3f268027-765d-4988-91d9-f0f948e6f9bc', '9466f5f0-09f2-4b9f-bb4a-3de270fd425b', 'b69e6150-0309-4202-bf4a-9a342f80d6d7', 'c5267964-d5b9-40a2-badf-c6461730549d', '35cd9ace-642f-4550-8e63-a5c2caae89ed', '09fb5412-80b9-49f0-841b-561a331ced64', '5ccb96c6-714f-4a93-9352-540899b27a4d', 'd752aedb-caf6-4e14-a98c-26d4e37eb144', 'bfea3e01-55f4-4744-a7c6-4494c7b99ef2', '864371ec-e13b-44ad-8e24-034d7506065a', 'ec4a3ba3-eb00-4aa8-9b41-36043ece98f7', '89f7ac43-956d-4d7e-b8a1-442ecff20ad6', '84aae2af-1a45-4e2a-ac52-eb7aeffe212d', '47c24350-cc10-4ec6-8407-24f778981a82', '7ffdd947-6154-4612-9638-319283e9088e', '18dc6a76-ae84-415f-9283-c1e35809b9ec', '4cdbfa59-948c-4afd-be5e-6e66fdbfcb19', '12babcc1-a848-4882-869e-b6e8cc963c2c', '1945d70d-bb9d-4523-aa31-7cfedb76b6c6', '7bf24899-4a05-46d4-b47d-36ce045643d8', '6525fb54-a95a-42cf-96b2-5767860e352d', 'ce835abe-d7f3-47bc-8d5e-c9b7eb0aef85']

In [24]:
print(len(subdirs))

42

In [25]:
import pandas as pd

In [26]:
text_embeddings_df = pd.read_csv("/scratch/yag1/ego4d_data/v2/queries_with_talk_and_paths.csv")

In [27]:
text_embeddings_df.head()

,clip_id,query,query_start_sec,query_end_sec,query_duration,clap_query,videoprism_query,clap_text_embedding_path,video_prism_text_embedding_path,qwen_text_embedding_path
0,a325ce85-cae5-4faa-99bb-7272918fcf19,when did i talk to the cashier at the store,403.38680,408.57537,5.18857,The sound of a person talking to the cashier a...,A video of a person talking to the cashier at ...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...
1,a325ce85-cae5-4faa-99bb-7272918fcf19,who did i talk to in the supermarket,404.36400,405.51063,1.14663,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...
2,b69e6150-0309-4202-bf4a-9a342f80d6d7,who did i talk to in the kitchen?,84.48200,88.18600,3.70400,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...
3,35cd9ace-642f-4550-8e63-a5c2caae89ed,who did i talk to in the workshop?,176.98861,180.98800,3.99939,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...
4,35cd9ace-642f-4550-8e63-a5c2caae89ed,who did i talk to in the workshop?,301.55537,323.55500,21.99963,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...

In [28]:
text_embeddings_df

,clip_id,query,query_start_sec,query_end_sec,query_duration,clap_query,videoprism_query,clap_text_embedding_path,video_prism_text_embedding_path,qwen_text_embedding_path
0,a325ce85-cae5-4faa-99bb-7272918fcf19,when did i talk to the cashier at the store,403.38680,408.57537,5.18857,The sound of a person talking to the cashier a...,A video of a person talking to the cashier at ...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...
1,a325ce85-cae5-4faa-99bb-7272918fcf19,who did i talk to in the supermarket,404.36400,405.51063,1.14663,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...
2,b69e6150-0309-4202-bf4a-9a342f80d6d7,who did i talk to in the kitchen?,84.48200,88.18600,3.70400,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...
3,35cd9ace-642f-4550-8e63-a5c2caae89ed,who did i talk to in the workshop?,176.98861,180.98800,3.99939,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...
4,35cd9ace-642f-4550-8e63-a5c2caae89ed,who did i talk to in the workshop?,301.55537,323.55500,21.99963,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...
5,3f268027-765d-4988-91d9-f0f948e6f9bc,who did i talk to when i was picking up the ba...,139.11411,140.00000,0.88589,The sound of a person talking to someone while...,A video of a person talking to someone while p...,/scratch/yag1/ego4d_data/v2/clips/3f268027-765...,/scratch/yag1/ego4d_data/v2/clips/3f268027-765...,/scratch/yag1/ego4d_data/v2/clips/3f268027-765...
6,18dc6a76-ae84-415f-9283-c1e35809b9ec,who did i talk to in the supermarket?,199.73075,201.00000,1.26925,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/18dc6a76-ae8...,/scratch/yag1/ego4d_data/v2/clips/18dc6a76-ae8...,/scratch/yag1/ego4d_data/v2/clips/18dc6a76-ae8...
7,7bf24899-4a05-46d4-b47d-36ce045643d8,who did i talk to when playing poker?,16.29892,23.00000,6.70108,The sound of a person talking to someone while...,A video of a person talking to someone when pl...,/scratch/yag1/ego4d_data/v2/clips/7bf24899-4a0...,/scratch/yag1/ego4d_data/v2/clips/7bf24899-4a0...,/scratch/yag1/ego4d_data/v2/clips/7bf24899-4a0...
8,7bf24899-4a05-46d4-b47d-36ce045643d8,who did i talk to when i was scrolling the phone?,279.47575,310.00000,30.52425,The sound of a person talking to someone while...,A video of a person talking to someone while s...,/scratch/yag1/ego4d_data/v2/clips/7bf24899-4a0...,/scratch/yag1/ego4d_data/v2/clips/7bf24899-4a0...,/scratch/yag1/ego4d_data/v2/clips/7bf24899-4a0...
9,1945d70d-bb9d-4523-aa31-7cfedb76b6c6,who did i talk to when i was playing cards?,330.55554,338.00000,7.44446,The sound of a person talking to someone while...,A video of a person talking to someone while p...,/scratch/yag1/ego4d_data/v2/clips/1945d70d-bb9...,/scratch/yag1/ego4d_data/v2/clips/1945d70d-bb9...,/scratch/yag1/ego4d_data/v2/clips/1945d70d-bb9...
10,780f7a41-3573-4dd6-8658-d1c8c02ef0ba,when did i talk with the cashier?,433.83603,434.28900,0.45297,The sound of a person talking with the cashier.,A video of a person talking with the cashier.,/scratch/yag1/ego4d_data/v2/clips/780f7a41-357...,/scratch/yag1/ego4d_data/v2/clips/780f7a41-357...,/scratch/yag1/ego4d_data/v2/clips/780f7a41-357...
11,15b03b30-201b-452b-948a-07571e4177c5,who did i talk to at the open kitchen?,269.92903,273.23400,3.30497,The sound of a person talking to someone at th...,A video of a person talking to someone at the ...,/scratch/yag1/ego4d_data/v2/clips/15b03b30-201...,/scratch/yag1/ego4d_data/v2/clips/15b03b30-201...,/scratch/yag1/ego4d_data/v2/clips/15b03b30-201...
12,1c433d54-a8fa-48ec-8fdf-1f8207e7ab38,who did i talk to in the workshop?,276.97905,282.00000,5.02095,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/1c433d54-a8f...,/scratch/yag1/ego4d_data/v2/clips/1c433d54-a8f...,/scratch/yag1/ego4d_data/v2/clips/1c433d54-a8f...
13,f4c804be-6a83-4f29-9e45-81bf6a2b00cb,when did i talk to the woman?,47.14457,49.06318,1.91861,The sound of a person talking to the woman.,A video of a person talking to the woman.,/scratch/yag1/ego4d_data/v2/clips/f4c804be-6a8...,/scratch/yag1/ego4d_data/v2/clips/f4c804be-6a8...,/scratch/yag1/ego4d_data/v2/clips/f4c804be-6a8...
14,cc2a687e-e871-4319-85c9-c0161678903d,who did i talk to in the living room?,81.35669,81.67481,0.31812,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/cc2a687e-e87...,/scratch/yag1/ego4d_data/v2/clips/cc2a687e-e87...,/scratch/yag1/ego4d_data/v2/clips/cc2a687e-e87...
15,93df179b-2bde-44e2-b0ea-e9c2c046dd3e,who did i talk to in a store?,27.11407,33.00000,5.88593,The sound of a person talking to someone in a ...,A video of a person talking to someone in a st...,/scratch/yag1/ego4d_data/v2/clips/93df179b-2bd...,/scratch/yag1/ego4d_data/v2/clips/93df179b-2bd...,/scratch/yag1/ego4d_data/v2/clips/93df179b-2bd...
16,47c24350-cc10-4ec6-8407-24f778981a82,who did i talk to when i was standing in the g...,69.00000,70.00000,1.00000,The sound of a person talking to someone while...,A video of a person talking to someone while s...,/scratch/yag1/ego4d_data/v2/clips/47c24350-cc1...,/scratch/yag1/ego4d_data/v2/clips/47c24350-cc1...,/scratch/yag1/ego4d_data/v2/clips/47c24350-cc1...
17,864371ec-e13b-44ad-8e24-034d7506065a,who did i talk to at the garage?,164.00000,165.00000,1.00000,The sound of a person talking to someone at th...,A video of a person talking to someone at the ...,/scratch/yag1/ego4d_data/v2/clips/864371ec-e13...,/scratch/yag1/ego4d_data/v2/clips/864371ec-e13...,/scratch/yag1/ego4d_data/v2/clips/864371ec-e13...
18,740a9d13-cf77-4e7d-91b5-a3ebf6d270ec,who did i talk to at the walkway?,442.95713,449.83600,6.87887,The sound of a person talking to someone at th...,A video of a person talking to someone at the ...,/scratch/yag1/ego4d_data/v2/clips/740a9d13-cf7...,/scratch/yag1/ego4d_data/v2/clips/740a9d13-cf7...,/scratch/yag1/ego4d_data/v2/clips/740a9d13-cf7...
19,9466f5f0-09f2-4b9f-bb4a-3de270fd425b,who did l talk to when l was in the garage?,218.82975,316.10700,97.27725,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/9466f5f0-09f...,/scratch/yag1/ego4d_data/v2/clips/9466f5f0-09f...,/scratch/yag1/ego4d_data/v2/clips/9466f5f0-09f...
20,9466f5f0-09f2-4b9f-bb4a-3de270fd425b,who did l talk to when l was in the garage?,399.63907,402.16700,2.52793,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/9466f5f0-09f...,/scratch/yag1/ego4d_data/v2/clips/9466f5f0-09f...,/scratch/yag1/ego4d_data/v2/clips/9466f5f0-09f...
21,ba5b8b24-2335-40c0-86c9-bfd76620e1fa,who did i talk to in the atm area.,439.13867,443.60345,4.46478,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/ba5b8b24-233...,/scratch/yag1/ego4d_data/v2/clips/ba5b8b24-233...,/scratch/yag1/ego4d_data/v2/clips/ba5b8b24-233...
22,ba5b8b24-2335-40c0-86c9-bfd76620e1fa,when did i talk to the person serving at the c...,1068.74241,1072.94551,4.20310,The sound of a person talking to the person se...,A video of a person talking to the person serv...,/scratch/yag1/ego4d_data/v2/clips/ba5b8b24-233...,/scratch/yag1/ego4d_data/v2/clips/ba5b8b24-233...,/scratch/yag1/ego4d_data/v2/clips/ba5b8b24-233...
23,f9fc7c0a-c42c-4c4c-a4ed-08f078ed5967,who did i talk to when i was placing the water...,271.66944,273.00000,1.33056,The sound of a person talking to someone while...,A video of a person talking to someone while p...,/scratch/yag1/ego4d_data/v2/clips/f9fc7c0a-c42...,/scratch/yag1/ego4d_data/v2/clips/f9fc7c0a-c42...,/scratch/yag1/ego4d_data/v2/clips/f9fc7c0a-c42...
24,d752aedb-caf6-4e14-a98c-26d4e37eb144,who did i talk to in the forest,473.74776,480.09600,6.34824,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/d752aedb-caf...,/scratch/yag1/ego4d_data/v2/clips/d752aedb-caf...,/scratch/yag1/ego4d_data/v2/clips/d752aedb-caf...
25,f15dbeca-63e7-43b5-b1a6-7896bc28b08c,who did l talk to in front of the boutique store,11.72260,17.00000,5.27740,The sound of a person talking to someone in fr...,A video of a person talking to someone in fron...,/scratch/yag1/ego4d_data/v2/clips/f15dbeca-63e...,/scratch/yag1/ego4d_data/v2/clips/f15dbeca-63e...,/scratch/yag1/ego4d_data/v2/clips/f15dbeca-63e...
26,f15dbeca-63e7-43b5-b1a6-7896bc28b08c,when did l talk to the cashier at the supermarket,282.51585,285.00000,2.48415,The sound of a person talking to the cashier a...,A video of a person talking to the cashier at ...,/scratch/yag1/ego4d_data/v2/clips/f15dbeca-63e...,/scratch/yag1/ego4d_data/v2/clips/f15dbeca-63e...,/scratch/yag1/ego4d_data/v2/clips/f15dbeca-63e...
27,c5267964-d5b9-40a2-badf-c6461730549d,query text:who did i talk to at the entrance o...,594.54712,631.59465,37.04753,The sound of a person talking to someone at th...,A video of a person talking to someone at the ...,/scratch/yag1/ego4d_data/v2/clips/c5267964-d5b...,/scratch/yag1/ego4d_data/v2/clips/c5267964-d5b...,/scratch/yag1/ego4d_data/v2/clips/c5267964-d5b...
28,c5267964-d5b9-40a2-badf-c6461730549d,who did i talk to on the porch?,728.01205,733.94967,5.93762,The sound of a person talking to someone on th...,A video of a person talking to someone on the ...,/scratch/yag1/ego4d_data/v2/clips/c5267964-d5b...,/scratch/yag1/ego4d_data/v2/clips/c5267964-d5b...,/scratch/yag1/ego4d_data/v2/clips/c5267964-d5b...
29,84aae2af-1a45-4e2a-ac52-eb7aeffe212d,who did i talk to in the study room?,84.81452,94.13400,9.31948,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/84aae2af-1a4...,/scratch/yag1/ego4d_data/v2/clips/84aae2af-1a4...,/scratch/yag1/ego4d_data/v2/clips/84aae2af-1a4...
30,b352dc19-c601-4740-9559-6db99ea782e9,who did i talk to near the counter?,9.36867,15.56200,6.19333,The sound of a person talking to someone near ...,A video of a person talking to someone near th...,/scratch/yag1/ego4d_data/v2/clips/b352dc19-c60...,/scratch/yag1/ego4d_data/v2/clips/b352dc19-c60...,/scratch/yag1/ego4d_data/v2/clips/b352dc19-c60...
31,b352dc19-c601-4740-9559-6db99ea782e9,when did i talk to the man who touched boxes o...,135.36319,138.32000,2.95681,The sound of a person talking to the man who t...,A video of a person talking to the man who tou...,/scratch/yag1/ego4d_data/v2/clips/b352dc19-c60...,/scratch/yag1/ego4d_data/v2/clips/b352dc19-c60...,/scratch/yag1/ego4d_data/v2/clips/b352dc19-c60...
32,3803f332-0ac4-4f11-92c7-319318859908,who did talk to in the house?,3.46286,13.00000,9.53714,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/3803f332-0ac...,/scratch/yag1/ego4d_data/v2/clips/3803f332-0ac...,/scratch/yag1/ego4d_data/v2/clips/3803f332-0ac...
33,bf629cf7-b95b-46db-b9b4-93a472057263,query text:whom did i talk to at the store?,469.55281,477.98354,8.43073,The sound of a person talking to someone at th...,A video of a person talking to someone at the ...,/scratch/yag1/ego4d_data/v2/clips/bf629cf7-b95...,/scratch/yag1/ego4d_data/v2/clips/bf629cf7-b95...,/scratch/yag1/ego4d_data/v2/clips/bf629cf7-b95...
34,ce835abe-d7f3-47bc-8d5e-c9b7eb0aef85,who did l talk to in the room?,418.12475,419.51100,1.38625,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/ce835abe-d7f...,/scratch/yag1/ego4d_data/v2/clips/ce835abe-d7f...,/scratch/yag1/ego4d_data/v2/clips/ce835abe-d7f...
35,54b5b878-d205-4a16-b945-62a7b08b577c,query text:who did i talk to when i was in the...,414.26846,422.84192,8.57346,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/54b5b878-d20...,/scratch/yag1/ego4d_data/v2/clips/54b5b878-d20...,/scratch/yag1/ego4d_data/v2/clips/54b5b878-d20...
36,b8e9a0cb-8a5d-467e-9ff0-873bdfa51037,query text:who did i talk to in the kitchen?,156.93183,162.30104,5.36921,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/b8e9a0cb-8a5...,/scratch/yag1/ego4d_data/v2/clips/b8e9a0cb-8a5...,/scratch/yag1/ego4d_data/v2/clips/b8e9a0cb-8a5...
37,12babcc1-a848-4882-869e-b6e8cc963c2c,when did i talk to with person y?,436.22447,437.00000,0.77553,The sound of a person talking to person y.,A video of a person talking to person y.,/scratch/yag1/ego4d_data/v2/clips/12babcc1-a84...,/scratch/yag1/ego4d_data/v2/clips/12babcc1-a84...,/scratch/yag1/ego4d_data/v2/clips/12babcc1-a84...
38,7ffdd947-6154-4612-9638-319283e9088e,who did i talk to in the clothe store?,242.22660,250.28900,8.06240,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/7ffdd947-615...,/scratch/yag1/ego4d_data/v2/clips/7ffdd947-615...,/scratch/yag1/ego4d_data/v2/clips/7ffdd947-615...
39,1731de62-b1b9-4b84-bd55-412cd67e9b3c,who did i talk to when i was eating?,114.15084,123.15000,8.99916,The sound of a person talking to someone while...,A video of a person talking to someone while e...,/scratch/yag1/ego4d_data/v2/clips/1731de62-b1b...,/scratch/yag1/ego4d_data/v2/clips/1731de62-b1b...,/scratch/yag1/ego4d_data/v2/clips/1731de62-b1b...
40,1731de62-b1b9-4b84-bd55-412cd67e9b3c,who did i talk to in the apartment?,243.47069,284.47000,40.99931,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/1731de62-b1b...,/scratch/yag1/ego4d_data/v2/clips/1731de62-b1b...,/scratch/yag1/ego4d_data/v2/clips/1731de62-b1b...
41,1731de62-b1b9-4b84-bd55-412cd67e9b3c,who did i talk to in the house?,62.33302,69.12800,6.79498,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/1731de62-b1b...,/scratch/yag1/ego4d_data/v2/clips/1731de62-b1b...,/scratch/yag1/ego4d_data/v2/clips/1731de62-b1b...
42,1731de62-b1b9-4b84-bd55-412cd67e9b3c,who did i talk to when i was eating the food?,247.93197,283.94000,36.00803,The sound of a person talking to someone while...,A video of a person talking to someone while e...,/scratch/yag1/ego4d_data/v2/clips/1731de62-b1b...,/scratch/yag1/ego4d_data/v2/clips/1731de62-b1b...,/scratch/yag1/ego4d_data/v2/clips/1731de62-b1b...
43,5ccb96c6-714f-4a93-9352-540899b27a4d,who did i talk to in the room?,26.37266,34.00000,7.62734,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/5ccb96c6-714...,/scratch/yag1/ego4d_data/v2/clips/5ccb96c6-714...,/scratch/yag1/ego4d_data/v2/clips/5ccb96c6-714...
44,d363833d-8f57-4a26-8b09-a1a4675c78c8,who did i talk to in a store?,52.31766,60.00000,7.68234,The sound of a person talking to someone in a ...,A video of a person talking to someone in a st...,/scratch/yag1/ego4d_data/v2/clips/d363833d-8f5...,/scratch/yag1/ego4d_data/v2/clips/d363833d-8f5...,/scratch/yag1/ego4d_data/v2/clips/d363833d-8f5...
45,09fb5412-80b9-49f0-841b-561a331ced64,who did i talk to in the house?,22.83198,26.18000,3.34802,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/09fb5412-80b...,/scratch/yag1/ego4d_data/v2/clips/09fb5412-80b...,/scratch/yag1/ego4d_data/v2/clips/09fb5412-80b...
46,fdb6c695-0a20-4c3d-b81c-80b0f9ec5187,who did i talk to in the sitting room?,0.00000,56.44441,56.44441,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/fdb6c695-0a2...,/scratch/yag1/ego4d_data/v2/clips/fdb6c695-0a2...,/scratch/yag1/ego4d_data/v2/clips/fdb6c695-0a2...
47,fdb6c695-0a20-4c3d-b81c-80b0f9ec5187,who did i talk to in the sitting room?,176.56915,184.37000,7.80085,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/fdb6c695-0a2...,/scratch/yag1/ego4d_data/v2/clips/fdb6c695-0a2...,/scratch/yag1/ego4d_data/v2/clips/fdb6c695-0a2...
48,ec4a3ba3-eb00-4aa8-9b41-36043ece98f7,who did i talk to when i was chopping the eggp...,214.00000,224.00000,10.00000,The sound of a person talking while chopping t...,A video of a person talking to someone while c...,/scratch/yag1/ego4d_data/v2/clips/ec4a3ba3-eb0...,/scratch/yag1/ego4d_data/v2/clips/ec4a3ba3-eb0...,/scratch/yag1/ego4d_data/v2/clips/ec4a3ba3-eb0...
49,6525fb54-a95a-42cf-96b2-5767860e352d,who did i talk to in the house?,109.40900,115.85400,6.44500,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/6525fb54-a95...,/scratch/yag1/ego4d_data/v2/clips/6525fb54-a95...,/scratch/yag1/ego4d_data/v2/clips/6525fb54-a95...
50,6525fb54-a95a-42cf-96b2-5767860e352d,who did i talk to in the house?,298.25563,306.36000,8.10437,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/6525fb54-a95...,/scratch/yag1/ego4d_data/v2/clips/6525fb54-a95...,/scratch/yag1/ego4d_data/v2/clips/6525fb54-a95...
51,89f7ac43-956d-4d7e-b8a1-442ecff20ad6,who did i talk to when i was shaking the cup?,80.20246,83.87419,3.67173,The sound of a person talking to someone while...,A video of a person talking to someone while s...,/scratch/yag1/ego4d_data/v2/clips/89f7ac43-956...,/scratch/yag1/ego4d_data/v2/clips/89f7ac43-956...,/scratch/yag1/ego4d_data/v2/clips/89f7ac43-956...
52,4cdbfa59-948c-4afd-be5e-6e66fdbfcb19,who did i talk to in the house?,310.92974,314.92900,3.99926,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/4cdbfa59-948...,/scratch/yag1/ego4d_data/v2/clips/4cdbfa59-948...,/scratch/yag1/ego4d_data/v2/clips/4cdbfa59-948...
53,bfea3e01-55f4-4744-a7c6-4494c7b99ef2,who did i talk to in the house?,397.99761,407.86223,9.86462,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/bfea3e01-55f...,/scratch/yag1/ego4d_data/v2/clips/bfea3e01-55f...,/scratch/yag1/ego4d_data/v2/clips/bfea3e01-55f...
54,3ef4d3b5-2a79-42f0-9609-509f886e7f93,who did i talk to at the road?,22.83426,24.22087,1.38661,The sound of a person talking to someone at th...,A video of a person talking to someone at the ...,/scratch/yag1/ego4d_data/v2/clips/3ef4d3b5-2a7...,/scratch/yag1/ego4d_data/v2/clips/3ef4d3b5-2a7...,/scratch/yag1/ego4d_data/v2/clips/3ef4d3b5-2a7...

In [29]:
embedding_dir = "qwen_video_embeddings"

In [30]:
import torch
import torch.nn.functional as F

In [31]:
def norm(embeddings):
  return F.normalize(embeddings, p=2, dim=1)# along each row

In [32]:
video_to_embedding = {}

In [33]:
for subdir in subdirs:
    video_embedding_path = Path(folder / subdir / embedding_dir)
    embedding_files = [p for p in video_embedding_path.iterdir() if p.is_file()]
    video_to_embedding[subdir] = [[], embedding_files]
    print(f"Processing {subdir} with {len(embedding_files)} embedding files")
    for embedding_file in embedding_files:
        video_to_embedding[subdir][0].append(torch.load(video_embedding_path / embedding_file))
    video_to_embedding[subdir][0] = norm(torch.stack(video_to_embedding[subdir][0], dim=0))
    print(video_to_embedding[subdir][0].shape)

Processing 15b03b30-201b-452b-948a-07571e4177c5 with 3177 embedding files
torch.Size([3177, 2048])
Processing ba5b8b24-2335-40c0-86c9-bfd76620e1fa with 14030 embedding files
torch.Size([14030, 2048])
Processing cc2a687e-e871-4319-85c9-c0161678903d with 2889 embedding files
torch.Size([2889, 2048])
Processing 740a9d13-cf77-4e7d-91b5-a3ebf6d270ec with 5320 embedding files
torch.Size([5320, 2048])
Processing 3ef4d3b5-2a79-42f0-9609-509f886e7f93 with 5602 embedding files
torch.Size([5602, 2048])
Processing 93df179b-2bde-44e2-b0ea-e9c2c046dd3e with 5237 embedding files
torch.Size([5237, 2048])
Processing 1731de62-b1b9-4b84-bd55-412cd67e9b3c with 5595 embedding files
torch.Size([5595, 2048])
Processing b8e9a0cb-8a5d-467e-9ff0-873bdfa51037 with 5602 embedding files
torch.Size([5602, 2048])
Processing f4c804be-6a83-4f29-9e45-81bf6a2b00cb with 4197 embedding files
torch.Size([4197, 2048])
Processing f9fc7c0a-c42c-4c4c-a4ed-08f078ed5967 with 5595 embedding files
torch.Size([5595, 2048])
Processing 780f7a41-3573-4dd6-8658-d1c8c02ef0ba with 5595 embedding files
torch.Size([5595, 2048])
Processing 54b5b878-d205-4a16-b945-62a7b08b577c with 4998 embedding files
torch.Size([4998, 2048])
Processing b352dc19-c601-4740-9559-6db99ea782e9 with 5595 embedding files
torch.Size([5595, 2048])
Processing 1c433d54-a8fa-48ec-8fdf-1f8207e7ab38 with 5602 embedding files
torch.Size([5602, 2048])
Processing 3803f332-0ac4-4f11-92c7-319318859908 with 14030 embedding files
torch.Size([14030, 2048])
Processing fdb6c695-0a20-4c3d-b81c-80b0f9ec5187 with 3265 embedding files
torch.Size([3265, 2048])
Processing d363833d-8f57-4a26-8b09-a1a4675c78c8 with 5595 embedding files
torch.Size([5595, 2048])
Processing bf629cf7-b95b-46db-b9b4-93a472057263 with 5602 embedding files
torch.Size([5602, 2048])
Processing a325ce85-cae5-4faa-99bb-7272918fcf19 with 5357 embedding files
torch.Size([5357, 2048])
Processing f15dbeca-63e7-43b5-b1a6-7896bc28b08c with 5602 embedding files
torch.Size([5602, 2048])
Processing 3f268027-765d-4988-91d9-f0f948e6f9bc with 5602 embedding files
torch.Size([5602, 2048])
Processing 9466f5f0-09f2-4b9f-bb4a-3de270fd425b with 5602 embedding files
torch.Size([5602, 2048])
Processing b69e6150-0309-4202-bf4a-9a342f80d6d7 with 5602 embedding files
torch.Size([5602, 2048])
Processing c5267964-d5b9-40a2-badf-c6461730549d with 14037 embedding files
torch.Size([14037, 2048])
Processing 35cd9ace-642f-4550-8e63-a5c2caae89ed with 5602 embedding files
torch.Size([5602, 2048])
Processing 09fb5412-80b9-49f0-841b-561a331ced64 with 5595 embedding files
torch.Size([5595, 2048])
Processing 5ccb96c6-714f-4a93-9352-540899b27a4d with 14030 embedding files
torch.Size([14030, 2048])
Processing d752aedb-caf6-4e14-a98c-26d4e37eb144 with 5602 embedding files
torch.Size([5602, 2048])
Processing bfea3e01-55f4-4744-a7c6-4494c7b99ef2 with 5595 embedding files
torch.Size([5595, 2048])
Processing 864371ec-e13b-44ad-8e24-034d7506065a with 3492 embedding files
torch.Size([3492, 2048])
Processing ec4a3ba3-eb00-4aa8-9b41-36043ece98f7 with 5595 embedding files
torch.Size([5595, 2048])
Processing 89f7ac43-956d-4d7e-b8a1-442ecff20ad6 with 5595 embedding files
torch.Size([5595, 2048])
Processing 84aae2af-1a45-4e2a-ac52-eb7aeffe212d with 5595 embedding files
torch.Size([5595, 2048])
Processing 47c24350-cc10-4ec6-8407-24f778981a82 with 3492 embedding files
torch.Size([3492, 2048])
Processing 7ffdd947-6154-4612-9638-319283e9088e with 3880 embedding files
torch.Size([3880, 2048])
Processing 18dc6a76-ae84-415f-9283-c1e35809b9ec with 5595 embedding files
torch.Size([5595, 2048])
Processing 4cdbfa59-948c-4afd-be5e-6e66fdbfcb19 with 5605 embedding files
torch.Size([5605, 2048])
Processing 12babcc1-a848-4882-869e-b6e8cc963c2c with 5595 embedding files
torch.Size([5595, 2048])
Processing 1945d70d-bb9d-4523-aa31-7cfedb76b6c6 with 4197 embedding files
torch.Size([4197, 2048])
Processing 7bf24899-4a05-46d4-b47d-36ce045643d8 with 5602 embedding files
torch.Size([5602, 2048])
Processing 6525fb54-a95a-42cf-96b2-5767860e352d with 5595 embedding files
torch.Size([5595, 2048])
Processing ce835abe-d7f3-47bc-8d5e-c9b7eb0aef85 with 4900 embedding files
torch.Size([4900, 2048])

In [34]:
embeddings = video_to_embedding[subdir][0]   # shape: [num_embeddings, dim]
norms = torch.linalg.norm(embeddings, dim=1)

print(norms[:10])
print("min:", norms.min().item())
print("max:", norms.max().item())
print("all close to 1:", torch.allclose(norms, torch.ones_like(norms), atol=1e-5))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='cuda:0',
       dtype=torch.bfloat16)
min: 1.0
max: 1.0
all close to 1: True

In [35]:
import faiss
import numpy as np

In [36]:
for k,v in video_to_embedding.items():
    base_index = faiss.IndexFlatIP(v[0].shape[1])  # dimension of embeddings
    faiss_index = faiss.IndexIDMap(base_index)
    
    id_array = np.arange(v[0].shape[0])  # unique IDs for each embedding
    faiss_index.add_with_ids(v[0].cpu().float().numpy(), id_array) # changed from bfloat16 to float32
    
    video_to_embedding[k].append(faiss_index)

#### Make Sure Types of Embeddings are correct

In [37]:
import ast

In [38]:
text_embeddings_df["qwen_distances"] = None
text_embeddings_df["qwen_indices"] = None
text_embeddings_df["qwen_min_distance"] = None
text_embeddings_df["qwen_max_distance"] = None

for clip_id, v in video_to_embedding.items():
    matching_rows = text_embeddings_df[
        text_embeddings_df["clip_id"] == clip_id
    ]

    for idx in matching_rows.index:
        path = text_embeddings_df.at[idx, "qwen_text_embedding_path"]

        query = norm(torch.load(path).unsqueeze(0))
        
        print(query.shape, query.dtype, query.device)
        
        
        D, I = v[2].search(query.numpy(), k=(v[2].ntotal))
        
        print(len(I[0]), len(D[0]), v[2].ntotal, clip_id, idx)

        text_embeddings_df.at[idx, "qwen_distances"] = D[0].tolist()
        text_embeddings_df.at[idx, "qwen_indices"] = I[0].tolist()
        text_embeddings_df.at[idx, "qwen_max_distance"] = D[0].max().item()
        text_embeddings_df.at[idx, "qwen_min_distance"] = D[0].min().item()

torch.Size([1, 2048]) torch.float32 cpu
3177 3177 3177 15b03b30-201b-452b-948a-07571e4177c5 11
torch.Size([1, 2048]) torch.float32 cpu
14030 14030 14030 ba5b8b24-2335-40c0-86c9-bfd76620e1fa 21
torch.Size([1, 2048]) torch.float32 cpu
14030 14030 14030 ba5b8b24-2335-40c0-86c9-bfd76620e1fa 22
torch.Size([1, 2048]) torch.float32 cpu
2889 2889 2889 cc2a687e-e871-4319-85c9-c0161678903d 14
torch.Size([1, 2048]) torch.float32 cpu
5320 5320 5320 740a9d13-cf77-4e7d-91b5-a3ebf6d270ec 18
torch.Size([1, 2048]) torch.float32 cpu
5602 5602 5602 3ef4d3b5-2a79-42f0-9609-509f886e7f93 54
torch.Size([1, 2048]) torch.float32 cpu
5237 5237 5237 93df179b-2bde-44e2-b0ea-e9c2c046dd3e 15
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 1731de62-b1b9-4b84-bd55-412cd67e9b3c 39
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 1731de62-b1b9-4b84-bd55-412cd67e9b3c 40
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 1731de62-b1b9-4b84-bd55-412cd67e9b3c 41
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 1731de62-b1b9-4b84-bd55-412cd67e9b3c 42
torch.Size([1, 2048]) torch.float32 cpu
5602 5602 5602 b8e9a0cb-8a5d-467e-9ff0-873bdfa51037 36
torch.Size([1, 2048]) torch.float32 cpu
4197 4197 4197 f4c804be-6a83-4f29-9e45-81bf6a2b00cb 13
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 f9fc7c0a-c42c-4c4c-a4ed-08f078ed5967 23
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 780f7a41-3573-4dd6-8658-d1c8c02ef0ba 10
torch.Size([1, 2048]) torch.float32 cpu
4998 4998 4998 54b5b878-d205-4a16-b945-62a7b08b577c 35
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 b352dc19-c601-4740-9559-6db99ea782e9 30
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 b352dc19-c601-4740-9559-6db99ea782e9 31
torch.Size([1, 2048]) torch.float32 cpu
5602 5602 5602 1c433d54-a8fa-48ec-8fdf-1f8207e7ab38 12
torch.Size([1, 2048]) torch.float32 cpu
14030 14030 14030 3803f332-0ac4-4f11-92c7-319318859908 32
torch.Size([1, 2048]) torch.float32 cpu
3265 3265 3265 fdb6c695-0a20-4c3d-b81c-80b0f9ec5187 46
torch.Size([1, 2048]) torch.float32 cpu
3265 3265 3265 fdb6c695-0a20-4c3d-b81c-80b0f9ec5187 47
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 d363833d-8f57-4a26-8b09-a1a4675c78c8 44
torch.Size([1, 2048]) torch.float32 cpu
5602 5602 5602 bf629cf7-b95b-46db-b9b4-93a472057263 33
torch.Size([1, 2048]) torch.float32 cpu
5357 5357 5357 a325ce85-cae5-4faa-99bb-7272918fcf19 0
torch.Size([1, 2048]) torch.float32 cpu
5357 5357 5357 a325ce85-cae5-4faa-99bb-7272918fcf19 1
torch.Size([1, 2048]) torch.float32 cpu
5602 5602 5602 f15dbeca-63e7-43b5-b1a6-7896bc28b08c 25
torch.Size([1, 2048]) torch.float32 cpu
5602 5602 5602 f15dbeca-63e7-43b5-b1a6-7896bc28b08c 26
torch.Size([1, 2048]) torch.float32 cpu
5602 5602 5602 3f268027-765d-4988-91d9-f0f948e6f9bc 5
torch.Size([1, 2048]) torch.float32 cpu
5602 5602 5602 9466f5f0-09f2-4b9f-bb4a-3de270fd425b 19
torch.Size([1, 2048]) torch.float32 cpu
5602 5602 5602 9466f5f0-09f2-4b9f-bb4a-3de270fd425b 20
torch.Size([1, 2048]) torch.float32 cpu
5602 5602 5602 b69e6150-0309-4202-bf4a-9a342f80d6d7 2
torch.Size([1, 2048]) torch.float32 cpu
14037 14037 14037 c5267964-d5b9-40a2-badf-c6461730549d 27
torch.Size([1, 2048]) torch.float32 cpu
14037 14037 14037 c5267964-d5b9-40a2-badf-c6461730549d 28
torch.Size([1, 2048]) torch.float32 cpu
5602 5602 5602 35cd9ace-642f-4550-8e63-a5c2caae89ed 3
torch.Size([1, 2048]) torch.float32 cpu
5602 5602 5602 35cd9ace-642f-4550-8e63-a5c2caae89ed 4
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 09fb5412-80b9-49f0-841b-561a331ced64 45
torch.Size([1, 2048]) torch.float32 cpu
14030 14030 14030 5ccb96c6-714f-4a93-9352-540899b27a4d 43
torch.Size([1, 2048]) torch.float32 cpu
5602 5602 5602 d752aedb-caf6-4e14-a98c-26d4e37eb144 24
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 bfea3e01-55f4-4744-a7c6-4494c7b99ef2 53
torch.Size([1, 2048]) torch.float32 cpu
3492 3492 3492 864371ec-e13b-44ad-8e24-034d7506065a 17
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 ec4a3ba3-eb00-4aa8-9b41-36043ece98f7 48
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 89f7ac43-956d-4d7e-b8a1-442ecff20ad6 51
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 84aae2af-1a45-4e2a-ac52-eb7aeffe212d 29
torch.Size([1, 2048]) torch.float32 cpu
3492 3492 3492 47c24350-cc10-4ec6-8407-24f778981a82 16
torch.Size([1, 2048]) torch.float32 cpu
3880 3880 3880 7ffdd947-6154-4612-9638-319283e9088e 38
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 18dc6a76-ae84-415f-9283-c1e35809b9ec 6
torch.Size([1, 2048]) torch.float32 cpu
5605 5605 5605 4cdbfa59-948c-4afd-be5e-6e66fdbfcb19 52
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 12babcc1-a848-4882-869e-b6e8cc963c2c 37
torch.Size([1, 2048]) torch.float32 cpu
4197 4197 4197 1945d70d-bb9d-4523-aa31-7cfedb76b6c6 9
torch.Size([1, 2048]) torch.float32 cpu
5602 5602 5602 7bf24899-4a05-46d4-b47d-36ce045643d8 7
torch.Size([1, 2048]) torch.float32 cpu
5602 5602 5602 7bf24899-4a05-46d4-b47d-36ce045643d8 8
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 6525fb54-a95a-42cf-96b2-5767860e352d 49
torch.Size([1, 2048]) torch.float32 cpu
5595 5595 5595 6525fb54-a95a-42cf-96b2-5767860e352d 50
torch.Size([1, 2048]) torch.float32 cpu
4900 4900 4900 ce835abe-d7f3-47bc-8d5e-c9b7eb0aef85 34

In [39]:
text_embeddings_df.head()

,clip_id,query,query_start_sec,query_end_sec,query_duration,clap_query,videoprism_query,clap_text_embedding_path,video_prism_text_embedding_path,qwen_text_embedding_path,qwen_distances,qwen_indices,qwen_min_distance,qwen_max_distance
0,a325ce85-cae5-4faa-99bb-7272918fcf19,when did i talk to the cashier at the store,403.38680,408.57537,5.18857,The sound of a person talking to the cashier a...,A video of a person talking to the cashier at ...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,"[0.7256371974945068, 0.722983717918396, 0.7215...","[1238, 1259, 1271, 2454, 1272, 1237, 4178, 124...",0.232926,0.725637
1,a325ce85-cae5-4faa-99bb-7272918fcf19,who did i talk to in the supermarket,404.36400,405.51063,1.14663,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,"[0.6930233240127563, 0.6921203136444092, 0.691...","[1833, 1831, 1827, 1829, 1828, 1832, 1830, 182...",0.25195,0.693023
2,b69e6150-0309-4202-bf4a-9a342f80d6d7,who did i talk to in the kitchen?,84.48200,88.18600,3.70400,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,"[0.6943589448928833, 0.686525821685791, 0.6846...","[41, 40, 42, 336, 43, 73, 39, 2887, 2988, 44, ...",0.275968,0.694359
3,35cd9ace-642f-4550-8e63-a5c2caae89ed,who did i talk to in the workshop?,176.98861,180.98800,3.99939,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,"[0.7163191437721252, 0.7093970775604248, 0.705...","[1559, 1560, 1557, 2696, 2697, 1558, 1215, 480...",0.293631,0.716319
4,35cd9ace-642f-4550-8e63-a5c2caae89ed,who did i talk to in the workshop?,301.55537,323.55500,21.99963,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,"[0.7163191437721252, 0.7093970775604248, 0.705...","[1559, 1560, 1557, 2696, 2697, 1558, 1215, 480...",0.293631,0.716319

In [40]:
text_embeddings_df["qwen_indices_unique"] = text_embeddings_df["qwen_indices"].apply(
    lambda x: len(x) == len(set(x))
)

In [41]:
text_embeddings_df["qwen_indices_unique"].value_counts()

qwen_indices_unique
True    55
Name: count, dtype: int64

In [42]:
text_embeddings_df.to_csv("/scratch/yag1/ego4d_data/v2/queries_with_talk_and_paths_and_qwen_retrieval.csv", index=False)