In [20]:
from pathlib import Path

folder = Path("/scratch/yag1/ego4d_data/v2/clips")

subdirs = [p.name for p in folder.iterdir() if p.is_dir()]
print(subdirs)

['15b03b30-201b-452b-948a-07571e4177c5', 'ba5b8b24-2335-40c0-86c9-bfd76620e1fa', 'cc2a687e-e871-4319-85c9-c0161678903d', '740a9d13-cf77-4e7d-91b5-a3ebf6d270ec', '3ef4d3b5-2a79-42f0-9609-509f886e7f93', '93df179b-2bde-44e2-b0ea-e9c2c046dd3e', '1731de62-b1b9-4b84-bd55-412cd67e9b3c', 'b8e9a0cb-8a5d-467e-9ff0-873bdfa51037', 'f4c804be-6a83-4f29-9e45-81bf6a2b00cb', 'f9fc7c0a-c42c-4c4c-a4ed-08f078ed5967', '780f7a41-3573-4dd6-8658-d1c8c02ef0ba', '54b5b878-d205-4a16-b945-62a7b08b577c', 'b352dc19-c601-4740-9559-6db99ea782e9', '1c433d54-a8fa-48ec-8fdf-1f8207e7ab38', '3803f332-0ac4-4f11-92c7-319318859908', 'fdb6c695-0a20-4c3d-b81c-80b0f9ec5187', 'd363833d-8f57-4a26-8b09-a1a4675c78c8', 'bf629cf7-b95b-46db-b9b4-93a472057263', 'a325ce85-cae5-4faa-99bb-7272918fcf19', 'f15dbeca-63e7-43b5-b1a6-7896bc28b08c', '3f268027-765d-4988-91d9-f0f948e6f9bc', '9466f5f0-09f2-4b9f-bb4a-3de270fd425b', 'b69e6150-0309-4202-bf4a-9a342f80d6d7', 'c5267964-d5b9-40a2-badf-c6461730549d', '35cd9ace-642f-4550-8e63-a5c2caae89ed', '09fb5412-80b9-49f0-841b-561a331ced64', '5ccb96c6-714f-4a93-9352-540899b27a4d', 'd752aedb-caf6-4e14-a98c-26d4e37eb144', 'bfea3e01-55f4-4744-a7c6-4494c7b99ef2', '864371ec-e13b-44ad-8e24-034d7506065a', 'ec4a3ba3-eb00-4aa8-9b41-36043ece98f7', '89f7ac43-956d-4d7e-b8a1-442ecff20ad6', '84aae2af-1a45-4e2a-ac52-eb7aeffe212d', '47c24350-cc10-4ec6-8407-24f778981a82', '7ffdd947-6154-4612-9638-319283e9088e', '18dc6a76-ae84-415f-9283-c1e35809b9ec', '4cdbfa59-948c-4afd-be5e-6e66fdbfcb19', '12babcc1-a848-4882-869e-b6e8cc963c2c', '1945d70d-bb9d-4523-aa31-7cfedb76b6c6', '7bf24899-4a05-46d4-b47d-36ce045643d8', '6525fb54-a95a-42cf-96b2-5767860e352d', 'ce835abe-d7f3-47bc-8d5e-c9b7eb0aef85']

In [21]:
print(len(subdirs))

42

In [22]:
import pandas as pd

In [23]:
text_embeddings_df = pd.read_csv("/scratch/yag1/ego4d_data/v2/queries_with_talk_and_paths_and_qwen_retrieval.csv")

In [24]:
text_embeddings_df.head()

,clip_id,query,query_start_sec,query_end_sec,query_duration,clap_query,videoprism_query,clap_text_embedding_path,video_prism_text_embedding_path,qwen_text_embedding_path,qwen_distances,qwen_indices,qwen_min_distance,qwen_max_distance,qwen_indices_unique
0,a325ce85-cae5-4faa-99bb-7272918fcf19,when did i talk to the cashier at the store,403.38680,408.57537,5.18857,The sound of a person talking to the cashier a...,A video of a person talking to the cashier at ...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,"[0.7256371974945068, 0.722983717918396, 0.7215...","[1238, 1259, 1271, 2454, 1272, 1237, 4178, 124...",0.232926,0.725637,True
1,a325ce85-cae5-4faa-99bb-7272918fcf19,who did i talk to in the supermarket,404.36400,405.51063,1.14663,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,"[0.6930233240127563, 0.6921203136444092, 0.691...","[1833, 1831, 1827, 1829, 1828, 1832, 1830, 182...",0.251950,0.693023,True
2,b69e6150-0309-4202-bf4a-9a342f80d6d7,who did i talk to in the kitchen?,84.48200,88.18600,3.70400,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,"[0.6943589448928833, 0.686525821685791, 0.6846...","[41, 40, 42, 336, 43, 73, 39, 2887, 2988, 44, ...",0.275968,0.694359,True
3,35cd9ace-642f-4550-8e63-a5c2caae89ed,who did i talk to in the workshop?,176.98861,180.98800,3.99939,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,"[0.7163191437721252, 0.7093970775604248, 0.705...","[1559, 1560, 1557, 2696, 2697, 1558, 1215, 480...",0.293631,0.716319,True
4,35cd9ace-642f-4550-8e63-a5c2caae89ed,who did i talk to in the workshop?,301.55537,323.55500,21.99963,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,"[0.7163191437721252, 0.7093970775604248, 0.705...","[1559, 1560, 1557, 2696, 2697, 1558, 1215, 480...",0.293631,0.716319,True

In [25]:
embedding_dir = "audio_embeddings"

In [26]:
import torch
import torch.nn.functional as F

In [27]:
def norm(embeddings):
  return F.normalize(embeddings, p=2, dim=1)# along each row

In [28]:
audio_to_embedding = {}

In [29]:
for subdir in subdirs:
    audio_embedding_path = Path(folder / subdir / embedding_dir)
    embedding_files = [p for p in audio_embedding_path.iterdir() if p.is_file()]
    audio_to_embedding[subdir] = [[], embedding_files]
    print(f"Processing {subdir} with {len(embedding_files)} embedding files")
    for embedding_file in embedding_files:
        audio_to_embedding[subdir][0].append(torch.load(audio_embedding_path / embedding_file))
    audio_to_embedding[subdir][0] = norm(torch.stack(audio_to_embedding[subdir][0], dim=0))
    print(audio_to_embedding[subdir][0].shape)

Processing 15b03b30-201b-452b-948a-07571e4177c5 with 3177 embedding files
torch.Size([3177, 512])
Processing ba5b8b24-2335-40c0-86c9-bfd76620e1fa with 14030 embedding files
torch.Size([14030, 512])
Processing cc2a687e-e871-4319-85c9-c0161678903d with 2889 embedding files
torch.Size([2889, 512])
Processing 740a9d13-cf77-4e7d-91b5-a3ebf6d270ec with 5320 embedding files
torch.Size([5320, 512])
Processing 3ef4d3b5-2a79-42f0-9609-509f886e7f93 with 5602 embedding files
torch.Size([5602, 512])
Processing 93df179b-2bde-44e2-b0ea-e9c2c046dd3e with 5237 embedding files
torch.Size([5237, 512])
Processing 1731de62-b1b9-4b84-bd55-412cd67e9b3c with 5595 embedding files
torch.Size([5595, 512])
Processing b8e9a0cb-8a5d-467e-9ff0-873bdfa51037 with 5602 embedding files
torch.Size([5602, 512])
Processing f4c804be-6a83-4f29-9e45-81bf6a2b00cb with 4197 embedding files
torch.Size([4197, 512])
Processing f9fc7c0a-c42c-4c4c-a4ed-08f078ed5967 with 5595 embedding files
torch.Size([5595, 512])
Processing 780f7a41-3573-4dd6-8658-d1c8c02ef0ba with 5595 embedding files
torch.Size([5595, 512])
Processing 54b5b878-d205-4a16-b945-62a7b08b577c with 4998 embedding files
torch.Size([4998, 512])
Processing b352dc19-c601-4740-9559-6db99ea782e9 with 5595 embedding files
torch.Size([5595, 512])
Processing 1c433d54-a8fa-48ec-8fdf-1f8207e7ab38 with 5602 embedding files
torch.Size([5602, 512])
Processing 3803f332-0ac4-4f11-92c7-319318859908 with 14030 embedding files
torch.Size([14030, 512])
Processing fdb6c695-0a20-4c3d-b81c-80b0f9ec5187 with 3265 embedding files
torch.Size([3265, 512])
Processing d363833d-8f57-4a26-8b09-a1a4675c78c8 with 5595 embedding files
torch.Size([5595, 512])
Processing bf629cf7-b95b-46db-b9b4-93a472057263 with 5602 embedding files
torch.Size([5602, 512])
Processing a325ce85-cae5-4faa-99bb-7272918fcf19 with 5357 embedding files
torch.Size([5357, 512])
Processing f15dbeca-63e7-43b5-b1a6-7896bc28b08c with 5602 embedding files
torch.Size([5602, 512])
Processing 3f268027-765d-4988-91d9-f0f948e6f9bc with 5602 embedding files
torch.Size([5602, 512])
Processing 9466f5f0-09f2-4b9f-bb4a-3de270fd425b with 5602 embedding files
torch.Size([5602, 512])
Processing b69e6150-0309-4202-bf4a-9a342f80d6d7 with 5602 embedding files
torch.Size([5602, 512])
Processing c5267964-d5b9-40a2-badf-c6461730549d with 14037 embedding files
torch.Size([14037, 512])
Processing 35cd9ace-642f-4550-8e63-a5c2caae89ed with 5602 embedding files
torch.Size([5602, 512])
Processing 09fb5412-80b9-49f0-841b-561a331ced64 with 5595 embedding files
torch.Size([5595, 512])
Processing 5ccb96c6-714f-4a93-9352-540899b27a4d with 14030 embedding files
torch.Size([14030, 512])
Processing d752aedb-caf6-4e14-a98c-26d4e37eb144 with 5602 embedding files
torch.Size([5602, 512])
Processing bfea3e01-55f4-4744-a7c6-4494c7b99ef2 with 5595 embedding files
torch.Size([5595, 512])
Processing 864371ec-e13b-44ad-8e24-034d7506065a with 3492 embedding files
torch.Size([3492, 512])
Processing ec4a3ba3-eb00-4aa8-9b41-36043ece98f7 with 5595 embedding files
torch.Size([5595, 512])
Processing 89f7ac43-956d-4d7e-b8a1-442ecff20ad6 with 5595 embedding files
torch.Size([5595, 512])
Processing 84aae2af-1a45-4e2a-ac52-eb7aeffe212d with 5595 embedding files
torch.Size([5595, 512])
Processing 47c24350-cc10-4ec6-8407-24f778981a82 with 3492 embedding files
torch.Size([3492, 512])
Processing 7ffdd947-6154-4612-9638-319283e9088e with 3880 embedding files
torch.Size([3880, 512])
Processing 18dc6a76-ae84-415f-9283-c1e35809b9ec with 5595 embedding files
torch.Size([5595, 512])
Processing 4cdbfa59-948c-4afd-be5e-6e66fdbfcb19 with 5605 embedding files
torch.Size([5605, 512])
Processing 12babcc1-a848-4882-869e-b6e8cc963c2c with 5595 embedding files
torch.Size([5595, 512])
Processing 1945d70d-bb9d-4523-aa31-7cfedb76b6c6 with 4197 embedding files
torch.Size([4197, 512])
Processing 7bf24899-4a05-46d4-b47d-36ce045643d8 with 5602 embedding files
torch.Size([5602, 512])
Processing 6525fb54-a95a-42cf-96b2-5767860e352d with 5595 embedding files
torch.Size([5595, 512])
Processing ce835abe-d7f3-47bc-8d5e-c9b7eb0aef85 with 4900 embedding files
torch.Size([4900, 512])

In [30]:
embeddings = audio_to_embedding[subdir][0]   # shape: [num_embeddings, dim]
norms = torch.linalg.norm(embeddings, dim=1)

print(norms[:10])
print("min:", norms.min().item())
print("max:", norms.max().item())
print("all close to 1:", torch.allclose(norms, torch.ones_like(norms), atol=1e-5))

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000])
min: 0.9999998807907104
max: 1.0000001192092896
all close to 1: True

In [31]:
import faiss
import numpy as np

In [32]:
for k,v in audio_to_embedding.items():
    base_index = faiss.IndexFlatIP(v[0].shape[1])  # dimension of embeddings
    faiss_index = faiss.IndexIDMap(base_index)
    
    id_array = np.arange(v[0].shape[0])  # unique IDs for each embedding
    faiss_index.add_with_ids(v[0].numpy(), id_array)
    
    audio_to_embedding[k].append(faiss_index)

In [33]:
import ast

In [34]:
text_embeddings_df["clap_distances"] = None
text_embeddings_df["clap_indices"] = None
text_embeddings_df["clap_min_distance"] = None
text_embeddings_df["clap_max_distance"] = None

for clip_id, v in audio_to_embedding.items():
    matching_rows = text_embeddings_df[
        text_embeddings_df["clip_id"] == clip_id
    ]

    for idx in matching_rows.index:
        path = text_embeddings_df.at[idx, "clap_text_embedding_path"]

        query = norm(torch.load(path).unsqueeze(0))
        
        D, I = v[2].search(query.numpy(), k=(v[2].ntotal))
        
        print(len(I[0]), len(D[0]), v[2].ntotal, clip_id, idx)

        text_embeddings_df.at[idx, "clap_distances"] = D[0].tolist()
        text_embeddings_df.at[idx, "clap_indices"] = I[0].tolist()
        text_embeddings_df.at[idx, "clap_max_distance"] = D[0].max().item()
        text_embeddings_df.at[idx, "clap_min_distance"] = D[0].min().item()

3177 3177 3177 15b03b30-201b-452b-948a-07571e4177c5 11
14030 14030 14030 ba5b8b24-2335-40c0-86c9-bfd76620e1fa 21
14030 14030 14030 ba5b8b24-2335-40c0-86c9-bfd76620e1fa 22
2889 2889 2889 cc2a687e-e871-4319-85c9-c0161678903d 14
5320 5320 5320 740a9d13-cf77-4e7d-91b5-a3ebf6d270ec 18
5602 5602 5602 3ef4d3b5-2a79-42f0-9609-509f886e7f93 54
5237 5237 5237 93df179b-2bde-44e2-b0ea-e9c2c046dd3e 15
5595 5595 5595 1731de62-b1b9-4b84-bd55-412cd67e9b3c 39
5595 5595 5595 1731de62-b1b9-4b84-bd55-412cd67e9b3c 40
5595 5595 5595 1731de62-b1b9-4b84-bd55-412cd67e9b3c 41
5595 5595 5595 1731de62-b1b9-4b84-bd55-412cd67e9b3c 42
5602 5602 5602 b8e9a0cb-8a5d-467e-9ff0-873bdfa51037 36
4197 4197 4197 f4c804be-6a83-4f29-9e45-81bf6a2b00cb 13
5595 5595 5595 f9fc7c0a-c42c-4c4c-a4ed-08f078ed5967 23
5595 5595 5595 780f7a41-3573-4dd6-8658-d1c8c02ef0ba 10
4998 4998 4998 54b5b878-d205-4a16-b945-62a7b08b577c 35
5595 5595 5595 b352dc19-c601-4740-9559-6db99ea782e9 30
5595 5595 5595 b352dc19-c601-4740-9559-6db99ea782e9 31
5602 5602 5602 1c433d54-a8fa-48ec-8fdf-1f8207e7ab38 12
14030 14030 14030 3803f332-0ac4-4f11-92c7-319318859908 32
3265 3265 3265 fdb6c695-0a20-4c3d-b81c-80b0f9ec5187 46
3265 3265 3265 fdb6c695-0a20-4c3d-b81c-80b0f9ec5187 47
5595 5595 5595 d363833d-8f57-4a26-8b09-a1a4675c78c8 44
5602 5602 5602 bf629cf7-b95b-46db-b9b4-93a472057263 33
5357 5357 5357 a325ce85-cae5-4faa-99bb-7272918fcf19 0
5357 5357 5357 a325ce85-cae5-4faa-99bb-7272918fcf19 1
5602 5602 5602 f15dbeca-63e7-43b5-b1a6-7896bc28b08c 25
5602 5602 5602 f15dbeca-63e7-43b5-b1a6-7896bc28b08c 26
5602 5602 5602 3f268027-765d-4988-91d9-f0f948e6f9bc 5
5602 5602 5602 9466f5f0-09f2-4b9f-bb4a-3de270fd425b 19
5602 5602 5602 9466f5f0-09f2-4b9f-bb4a-3de270fd425b 20
5602 5602 5602 b69e6150-0309-4202-bf4a-9a342f80d6d7 2
14037 14037 14037 c5267964-d5b9-40a2-badf-c6461730549d 27
14037 14037 14037 c5267964-d5b9-40a2-badf-c6461730549d 28
5602 5602 5602 35cd9ace-642f-4550-8e63-a5c2caae89ed 3
5602 5602 5602 35cd9ace-642f-4550-8e63-a5c2caae89ed 4
5595 5595 5595 09fb5412-80b9-49f0-841b-561a331ced64 45
14030 14030 14030 5ccb96c6-714f-4a93-9352-540899b27a4d 43
5602 5602 5602 d752aedb-caf6-4e14-a98c-26d4e37eb144 24
5595 5595 5595 bfea3e01-55f4-4744-a7c6-4494c7b99ef2 53
3492 3492 3492 864371ec-e13b-44ad-8e24-034d7506065a 17
5595 5595 5595 ec4a3ba3-eb00-4aa8-9b41-36043ece98f7 48
5595 5595 5595 89f7ac43-956d-4d7e-b8a1-442ecff20ad6 51
5595 5595 5595 84aae2af-1a45-4e2a-ac52-eb7aeffe212d 29
3492 3492 3492 47c24350-cc10-4ec6-8407-24f778981a82 16
3880 3880 3880 7ffdd947-6154-4612-9638-319283e9088e 38
5595 5595 5595 18dc6a76-ae84-415f-9283-c1e35809b9ec 6
5605 5605 5605 4cdbfa59-948c-4afd-be5e-6e66fdbfcb19 52
5595 5595 5595 12babcc1-a848-4882-869e-b6e8cc963c2c 37
4197 4197 4197 1945d70d-bb9d-4523-aa31-7cfedb76b6c6 9
5602 5602 5602 7bf24899-4a05-46d4-b47d-36ce045643d8 7
5602 5602 5602 7bf24899-4a05-46d4-b47d-36ce045643d8 8
5595 5595 5595 6525fb54-a95a-42cf-96b2-5767860e352d 49
5595 5595 5595 6525fb54-a95a-42cf-96b2-5767860e352d 50
4900 4900 4900 ce835abe-d7f3-47bc-8d5e-c9b7eb0aef85 34

In [35]:
text_embeddings_df.head()

,clip_id,query,query_start_sec,query_end_sec,query_duration,clap_query,videoprism_query,clap_text_embedding_path,video_prism_text_embedding_path,qwen_text_embedding_path,qwen_distances,qwen_indices,qwen_min_distance,qwen_max_distance,qwen_indices_unique,clap_distances,clap_indices,clap_min_distance,clap_max_distance
0,a325ce85-cae5-4faa-99bb-7272918fcf19,when did i talk to the cashier at the store,403.38680,408.57537,5.18857,The sound of a person talking to the cashier a...,A video of a person talking to the cashier at ...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,"[0.7256371974945068, 0.722983717918396, 0.7215...","[1238, 1259, 1271, 2454, 1272, 1237, 4178, 124...",0.232926,0.725637,True,"[0.6924006938934326, 0.6633265018463135, 0.655...","[512, 2091, 3488, 2632, 2633, 2922, 3440, 2869...",0.050811,0.692401
1,a325ce85-cae5-4faa-99bb-7272918fcf19,who did i talk to in the supermarket,404.36400,405.51063,1.14663,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,"[0.6930233240127563, 0.6921203136444092, 0.691...","[1833, 1831, 1827, 1829, 1828, 1832, 1830, 182...",0.251950,0.693023,True,"[0.6368874311447144, 0.5578994750976562, 0.554...","[512, 2922, 4727, 3935, 515, 4726, 4725, 2869,...",-0.055909,0.636887
2,b69e6150-0309-4202-bf4a-9a342f80d6d7,who did i talk to in the kitchen?,84.48200,88.18600,3.70400,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,"[0.6943589448928833, 0.686525821685791, 0.6846...","[41, 40, 42, 336, 43, 73, 39, 2887, 2988, 44, ...",0.275968,0.694359,True,"[0.5192633271217346, 0.5079946517944336, 0.507...","[4586, 5164, 5529, 4036, 4882, 5146, 4876, 458...",-0.060817,0.519263
3,35cd9ace-642f-4550-8e63-a5c2caae89ed,who did i talk to in the workshop?,176.98861,180.98800,3.99939,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,"[0.7163191437721252, 0.7093970775604248, 0.705...","[1559, 1560, 1557, 2696, 2697, 1558, 1215, 480...",0.293631,0.716319,True,"[0.5938727855682373, 0.571954071521759, 0.5242...","[4079, 5574, 2283, 3119, 4663, 4205, 4788, 507...",-0.078011,0.593873
4,35cd9ace-642f-4550-8e63-a5c2caae89ed,who did i talk to in the workshop?,301.55537,323.55500,21.99963,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,"[0.7163191437721252, 0.7093970775604248, 0.705...","[1559, 1560, 1557, 2696, 2697, 1558, 1215, 480...",0.293631,0.716319,True,"[0.5938727855682373, 0.571954071521759, 0.5242...","[4079, 5574, 2283, 3119, 4663, 4205, 4788, 507...",-0.078011,0.593873

In [36]:
text_embeddings_df["clap_indices_unique"] = text_embeddings_df["clap_indices"].apply(
    lambda x: len(x) == len(set(x))
)

In [37]:
text_embeddings_df["clap_indices_unique"].value_counts()

clap_indices_unique
True    55
Name: count, dtype: int64

In [38]:
text_embeddings_df.to_csv("/scratch/yag1/ego4d_data/v2/queries_with_talk_and_paths_with_qwen_and_audio_retrieval.csv", index=False)