In [1]:
import pandas as pd
import json
from pathlib import Path

In [2]:
retrieval_df = pd.read_csv("/scratch/yag1/ego4d_data/v2/queries_with_talk_and_paths_with_qwen_and_audio_retrieval.csv")
retrieval_df.head()

,clip_id,query,query_start_sec,query_end_sec,query_duration,clap_query,videoprism_query,clap_text_embedding_path,video_prism_text_embedding_path,qwen_text_embedding_path,qwen_distances,qwen_indices,qwen_min_distance,qwen_max_distance,qwen_indices_unique,clap_distances,clap_indices,clap_min_distance,clap_max_distance,clap_indices_unique
0,a325ce85-cae5-4faa-99bb-7272918fcf19,when did i talk to the cashier at the store,403.38680,408.57537,5.18857,The sound of a person talking to the cashier a...,A video of a person talking to the cashier at ...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,"[0.7256371974945068, 0.722983717918396, 0.7215...","[1238, 1259, 1271, 2454, 1272, 1237, 4178, 124...",0.232926,0.725637,True,"[0.6924006938934326, 0.6633265018463135, 0.655...","[512, 2091, 3488, 2632, 2633, 2922, 3440, 2869...",0.050811,0.692401,True
1,a325ce85-cae5-4faa-99bb-7272918fcf19,who did i talk to in the supermarket,404.36400,405.51063,1.14663,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,"[0.6930233240127563, 0.6921203136444092, 0.691...","[1833, 1831, 1827, 1829, 1828, 1832, 1830, 182...",0.251950,0.693023,True,"[0.6368874311447144, 0.5578994750976562, 0.554...","[512, 2922, 4727, 3935, 515, 4726, 4725, 2869,...",-0.055909,0.636887,True
2,b69e6150-0309-4202-bf4a-9a342f80d6d7,who did i talk to in the kitchen?,84.48200,88.18600,3.70400,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,"[0.6943589448928833, 0.686525821685791, 0.6846...","[41, 40, 42, 336, 43, 73, 39, 2887, 2988, 44, ...",0.275968,0.694359,True,"[0.5192633271217346, 0.5079946517944336, 0.507...","[4586, 5164, 5529, 4036, 4882, 5146, 4876, 458...",-0.060817,0.519263,True
3,35cd9ace-642f-4550-8e63-a5c2caae89ed,who did i talk to in the workshop?,176.98861,180.98800,3.99939,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,"[0.7163191437721252, 0.7093970775604248, 0.705...","[1559, 1560, 1557, 2696, 2697, 1558, 1215, 480...",0.293631,0.716319,True,"[0.5938727855682373, 0.571954071521759, 0.5242...","[4079, 5574, 2283, 3119, 4663, 4205, 4788, 507...",-0.078011,0.593873,True
4,35cd9ace-642f-4550-8e63-a5c2caae89ed,who did i talk to in the workshop?,301.55537,323.55500,21.99963,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,"[0.7163191437721252, 0.7093970775604248, 0.705...","[1559, 1560, 1557, 2696, 2697, 1558, 1215, 480...",0.293631,0.716319,True,"[0.5938727855682373, 0.571954071521759, 0.5242...","[4079, 5574, 2283, 3119, 4663, 4205, 4788, 507...",-0.078011,0.593873,True

In [3]:
root_dir = "/scratch/yag1/ego4d_data/v2/clips"

In [4]:
segments_by_duration = {}
for i in range(1, 11):
    with open(f"{i}_seconds_segments.json") as f:
        segments_by_duration[i] = json.load(f)

In [5]:
root_dir = Path(root_dir)

subdirs = [p.name for p in root_dir.iterdir() if p.is_dir()]

In [6]:
print(subdirs)

['15b03b30-201b-452b-948a-07571e4177c5', 'ba5b8b24-2335-40c0-86c9-bfd76620e1fa', 'cc2a687e-e871-4319-85c9-c0161678903d', '740a9d13-cf77-4e7d-91b5-a3ebf6d270ec', '3ef4d3b5-2a79-42f0-9609-509f886e7f93', '93df179b-2bde-44e2-b0ea-e9c2c046dd3e', '1731de62-b1b9-4b84-bd55-412cd67e9b3c', 'b8e9a0cb-8a5d-467e-9ff0-873bdfa51037', 'f4c804be-6a83-4f29-9e45-81bf6a2b00cb', 'f9fc7c0a-c42c-4c4c-a4ed-08f078ed5967', '780f7a41-3573-4dd6-8658-d1c8c02ef0ba', '54b5b878-d205-4a16-b945-62a7b08b577c', 'b352dc19-c601-4740-9559-6db99ea782e9', '1c433d54-a8fa-48ec-8fdf-1f8207e7ab38', '3803f332-0ac4-4f11-92c7-319318859908', 'fdb6c695-0a20-4c3d-b81c-80b0f9ec5187', 'd363833d-8f57-4a26-8b09-a1a4675c78c8', 'bf629cf7-b95b-46db-b9b4-93a472057263', 'a325ce85-cae5-4faa-99bb-7272918fcf19', 'f15dbeca-63e7-43b5-b1a6-7896bc28b08c', '3f268027-765d-4988-91d9-f0f948e6f9bc', '9466f5f0-09f2-4b9f-bb4a-3de270fd425b', 'b69e6150-0309-4202-bf4a-9a342f80d6d7', 'c5267964-d5b9-40a2-badf-c6461730549d', '35cd9ace-642f-4550-8e63-a5c2caae89ed', '09fb5412-80b9-49f0-841b-561a331ced64', '5ccb96c6-714f-4a93-9352-540899b27a4d', 'd752aedb-caf6-4e14-a98c-26d4e37eb144', 'bfea3e01-55f4-4744-a7c6-4494c7b99ef2', '864371ec-e13b-44ad-8e24-034d7506065a', 'ec4a3ba3-eb00-4aa8-9b41-36043ece98f7', '89f7ac43-956d-4d7e-b8a1-442ecff20ad6', '84aae2af-1a45-4e2a-ac52-eb7aeffe212d', '47c24350-cc10-4ec6-8407-24f778981a82', '7ffdd947-6154-4612-9638-319283e9088e', '18dc6a76-ae84-415f-9283-c1e35809b9ec', '4cdbfa59-948c-4afd-be5e-6e66fdbfcb19', '12babcc1-a848-4882-869e-b6e8cc963c2c', '1945d70d-bb9d-4523-aa31-7cfedb76b6c6', '7bf24899-4a05-46d4-b47d-36ce045643d8', '6525fb54-a95a-42cf-96b2-5767860e352d', 'ce835abe-d7f3-47bc-8d5e-c9b7eb0aef85']

In [7]:
print(len(subdirs))

42

In [8]:
from collections import defaultdict

In [9]:
index_mapping = defaultdict(dict)

In [10]:
for subdir in subdirs:
    files_in_subdir_audio = [p.name for p in (root_dir / subdir / "audio_embeddings").iterdir() if p.is_file()]
    files_in_subdir_video = [p.name for p in (root_dir / subdir / "video_embeddings").iterdir() if p.is_file()]
    # check that the lists are the same
    assert files_in_subdir_audio == files_in_subdir_video, f"Files in {subdir} don't match"
    for i, file in enumerate(files_in_subdir_audio):
        #split the filename based on underscores
        parts = file.split("_")
        # the last part is the timestamp with .pt at the end, so remove the .pt
        json_seconds_name = int(parts[0])
        json_index = int(parts[-1].replace(".pt", ""))
        
        time = segments_by_duration[json_seconds_name][str(root_dir / f"{subdir}.mp4")][json_index]
        
        index_mapping[subdir][i] = time

In [11]:
def match_indices_to_timestamps(clip_id, indices):
    timestamps = [index_mapping[clip_id][idx] for idx in indices]
    return timestamps

In [12]:
retrieval_df["video_retrieval_timestamps"] = retrieval_df.apply(lambda row: match_indices_to_timestamps(row["clip_id"], eval(row["qwen_indices"])), axis=1)
retrieval_df["audio_retrieval_timestamps"] = retrieval_df.apply(lambda row: match_indices_to_timestamps(row["clip_id"], eval(row["clap_indices"])), axis=1)

In [13]:
retrieval_df.head()

,clip_id,query,query_start_sec,query_end_sec,query_duration,clap_query,videoprism_query,clap_text_embedding_path,video_prism_text_embedding_path,qwen_text_embedding_path,...,qwen_min_distance,qwen_max_distance,qwen_indices_unique,clap_distances,clap_indices,clap_min_distance,clap_max_distance,clap_indices_unique,video_retrieval_timestamps,audio_retrieval_timestamps
0,a325ce85-cae5-4faa-99bb-7272918fcf19,when did i talk to the cashier at the store,403.38680,408.57537,5.18857,The sound of a person talking to the cashier a...,A video of a person talking to the cashier at ...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,...,0.232926,0.725637,True,"[0.6924006938934326, 0.6633265018463135, 0.655...","[512, 2091, 3488, 2632, 2633, 2922, 3440, 2869...",0.050811,0.692401,True,"[[309.5, 310.5], [314.75, 315.75], [317.75, 31...","[[128.0, 129.0], [128.0, 130.0], [127.0, 131.0..."
1,a325ce85-cae5-4faa-99bb-7272918fcf19,who did i talk to in the supermarket,404.36400,405.51063,1.14663,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,...,0.251950,0.693023,True,"[0.6368874311447144, 0.5578994750976562, 0.554...","[512, 2922, 4727, 3935, 515, 4726, 4725, 2869,...",-0.055909,0.636887,True,"[[458.25, 459.25], [457.75, 458.75], [456.75, ...","[[128.0, 129.0], [128.25, 131.25], [126.0, 133..."
2,b69e6150-0309-4202-bf4a-9a342f80d6d7,who did i talk to in the kitchen?,84.48200,88.18600,3.70400,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,...,0.275968,0.694359,True,"[0.5192633271217346, 0.5079946517944336, 0.507...","[4586, 5164, 5529, 4036, 4882, 5146, 4876, 458...",-0.060817,0.519263,True,"[[10.25, 11.25], [10.0, 11.0], [10.5, 11.5], [...","[[66.0, 72.0], [64.0, 72.0], [65.0, 75.0], [28..."
3,35cd9ace-642f-4550-8e63-a5c2caae89ed,who did i talk to in the workshop?,176.98861,180.98800,3.99939,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,...,0.293631,0.716319,True,"[0.5938727855682373, 0.571954071521759, 0.5242...","[4079, 5574, 2283, 3119, 4663, 4205, 4788, 507...",-0.078011,0.593873,True,"[[389.75, 390.75], [390.0, 391.0], [389.25, 39...","[[177.75, 186.75], [177.5, 187.5], [182.5, 184..."
4,35cd9ace-642f-4550-8e63-a5c2caae89ed,who did i talk to in the workshop?,301.55537,323.55500,21.99963,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,...,0.293631,0.716319,True,"[0.5938727855682373, 0.571954071521759, 0.5242...","[4079, 5574, 2283, 3119, 4663, 4205, 4788, 507...",-0.078011,0.593873,True,"[[389.75, 390.75], [390.0, 391.0], [389.25, 39...","[[177.75, 186.75], [177.5, 187.5], [182.5, 184..."

In [14]:
for index, row in retrieval_df.iterrows():
    video_sections = row["video_retrieval_timestamps"]
    audio_sections = row["audio_retrieval_timestamps"]
    assert len(video_sections) == len(audio_sections), f"Mismatch in lengths for clip_id {row['clip_id']} at index {index}"
    
    # convert every list of timestamps to a tuple so that we can check for duplicates
    video_sections_tup = [tuple(section) for section in video_sections]
    audio_sections_tup = [tuple(section) for section in audio_sections]
    
    assert len(video_sections) == len(set(video_sections_tup)), f"Duplicate timestamps in video sections for clip_id {row['clip_id']} at index {index}"
    
    assert len(audio_sections) == len(set(audio_sections_tup)), f"Duplicate timestamps in audio sections for clip_id {row['clip_id']} at index {index}"
    
    # print where there are duplicates
    if len(video_sections) != len(set(video_sections_tup)):
        print(f"Duplicate timestamps in video sections for clip_id {row['clip_id']} at index {index}")
        seen = set()
        duplicates = set()
        for section in video_sections_tup:
            if section in seen:
                duplicates.add(section)
            else:
                seen.add(section)
        print(f"Duplicate video timestamps: {duplicates}")

## Normal IoU computation

In [15]:
import numpy as np

In [16]:
def compute_IoU(pred, gt_start, gt_end):
    """Compute the IoU given predicted and ground truth windows."""
    gt = [[gt_start, gt_end]]
    assert isinstance(pred, list) and isinstance(gt, list)
    pred_is_list = isinstance(pred[0], list)
    gt_is_list = isinstance(gt[0], list)
    if not pred_is_list:
        pred = [pred]
    if not gt_is_list:
        gt = [gt]
    pred, gt = np.array(pred), np.array(gt)
    inter_left = np.maximum(pred[:, 0, None], gt[None, :, 0])
    inter_right = np.minimum(pred[:, 1, None], gt[None, :, 1])
    inter = np.maximum(0.0, inter_right - inter_left)
    union_left = np.minimum(pred[:, 0, None], gt[None, :, 0])
    union_right = np.maximum(pred[:, 1, None], gt[None, :, 1])
    union = np.maximum(0.0, union_right - union_left)
    overlap = 1.0 * inter / union
    if not gt_is_list:
        overlap = overlap[:, 0]
    if not pred_is_list:
        overlap = overlap[0]
    return overlap

In [17]:
retrieval_df["video_IoU"] = retrieval_df.apply(lambda row: compute_IoU(row["video_retrieval_timestamps"], row["query_start_sec"], row["query_end_sec"]), axis=1)
retrieval_df["audio_IoU"] = retrieval_df.apply(lambda row: compute_IoU(row["audio_retrieval_timestamps"], row["query_start_sec"], row["query_end_sec"]), axis=1)

In [18]:
retrieval_df.head()

,clip_id,query,query_start_sec,query_end_sec,query_duration,clap_query,videoprism_query,clap_text_embedding_path,video_prism_text_embedding_path,qwen_text_embedding_path,...,qwen_indices_unique,clap_distances,clap_indices,clap_min_distance,clap_max_distance,clap_indices_unique,video_retrieval_timestamps,audio_retrieval_timestamps,video_IoU,audio_IoU
0,a325ce85-cae5-4faa-99bb-7272918fcf19,when did i talk to the cashier at the store,403.38680,408.57537,5.18857,The sound of a person talking to the cashier a...,A video of a person talking to the cashier at ...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,...,True,"[0.6924006938934326, 0.6633265018463135, 0.655...","[512, 2091, 3488, 2632, 2633, 2922, 3440, 2869...",0.050811,0.692401,True,"[[309.5, 310.5], [314.75, 315.75], [317.75, 31...","[[128.0, 129.0], [128.0, 130.0], [127.0, 131.0...","[[0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0....","[[0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0...."
1,a325ce85-cae5-4faa-99bb-7272918fcf19,who did i talk to in the supermarket,404.36400,405.51063,1.14663,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,/scratch/yag1/ego4d_data/v2/clips/a325ce85-cae...,...,True,"[0.6368874311447144, 0.5578994750976562, 0.554...","[512, 2922, 4727, 3935, 515, 4726, 4725, 2869,...",-0.055909,0.636887,True,"[[458.25, 459.25], [457.75, 458.75], [456.75, ...","[[128.0, 129.0], [128.25, 131.25], [126.0, 133...","[[0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0....","[[0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0...."
2,b69e6150-0309-4202-bf4a-9a342f80d6d7,who did i talk to in the kitchen?,84.48200,88.18600,3.70400,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,/scratch/yag1/ego4d_data/v2/clips/b69e6150-030...,...,True,"[0.5192633271217346, 0.5079946517944336, 0.507...","[4586, 5164, 5529, 4036, 4882, 5146, 4876, 458...",-0.060817,0.519263,True,"[[10.25, 11.25], [10.0, 11.0], [10.5, 11.5], [...","[[66.0, 72.0], [64.0, 72.0], [65.0, 75.0], [28...","[[0.0], [0.0], [0.0], [0.12374581939799327], [...","[[0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0...."
3,35cd9ace-642f-4550-8e63-a5c2caae89ed,who did i talk to in the workshop?,176.98861,180.98800,3.99939,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,...,True,"[0.5938727855682373, 0.571954071521759, 0.5242...","[4079, 5574, 2283, 3119, 4663, 4205, 4788, 507...",-0.078011,0.593873,True,"[[389.75, 390.75], [390.0, 391.0], [389.25, 39...","[[177.75, 186.75], [177.5, 187.5], [182.5, 184...","[[0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0....","[[0.33171505287669045], [0.3318305190845357], ..."
4,35cd9ace-642f-4550-8e63-a5c2caae89ed,who did i talk to in the workshop?,301.55537,323.55500,21.99963,The sound of a person talking to someone in th...,A video of a person talking to someone in the ...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,/scratch/yag1/ego4d_data/v2/clips/35cd9ace-642...,...,True,"[0.5938727855682373, 0.571954071521759, 0.5242...","[4079, 5574, 2283, 3119, 4663, 4205, 4788, 507...",-0.078011,0.593873,True,"[[389.75, 390.75], [390.0, 391.0], [389.25, 39...","[[177.75, 186.75], [177.5, 187.5], [182.5, 184...","[[0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0....","[[0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0...."

In [19]:
def compute_recall_at_k(k_val, IoU_threshold, iou_list):
    """Compute recall at k given a list of IoU values."""
    top_k_iou = iou_list[:k_val]
    num_relevant = sum(iou >= IoU_threshold for iou in top_k_iou)
    return int((num_relevant > 0).item())

In [20]:
retrieval_df["video_IoU_recall_at_3_0.3"] = retrieval_df["video_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.3, iou_list))
retrieval_df["audio_IoU_recall_at_3_0.3"] = retrieval_df["audio_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.3, iou_list))

retrieval_df["video_IoU_recall_at_3_0.5"] = retrieval_df["video_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.5, iou_list))
retrieval_df["audio_IoU_recall_at_3_0.5"] = retrieval_df["audio_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.5, iou_list))

retrieval_df["video_IoU_recall_at_5_0.3"] = retrieval_df["video_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.3, iou_list))
retrieval_df["audio_IoU_recall_at_5_0.3"] = retrieval_df["audio_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.3, iou_list))

retrieval_df["video_IoU_recall_at_5_0.5"] = retrieval_df["video_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.5, iou_list))
retrieval_df["audio_IoU_recall_at_5_0.5"] = retrieval_df["audio_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.5, iou_list))

In [21]:
retrieval_df["video_IoU_mean_IoU_top_3"] = (retrieval_df["video_IoU_recall_at_3_0.3"] + retrieval_df["video_IoU_recall_at_3_0.5"]) / 2
retrieval_df["audio_IoU_mean_IoU_top_3"] = (retrieval_df["audio_IoU_recall_at_3_0.3"] + retrieval_df["audio_IoU_recall_at_3_0.5"]) / 2

retrieval_df["video_IoU_mean_IoU_top_5"] = (retrieval_df["video_IoU_recall_at_5_0.3"] + retrieval_df["video_IoU_recall_at_5_0.5"]) / 2
retrieval_df["audio_IoU_mean_IoU_top_5"] = (retrieval_df["audio_IoU_recall_at_5_0.3"] + retrieval_df["audio_IoU_recall_at_5_0.5"]) / 2

## Temporal NMS IoU computation

### IoU-based NMS

In [22]:
def temporal_iou(seg1, seg2):
    s1, e1 = seg1
    s2, e2 = seg2

    inter = max(0, min(e1, e2) - max(s1, s2))
    union = (e1 - s1) + (e2 - s2) - inter

    return inter / union if union > 0 else 0

In [23]:
def temporal_iom(seg1, seg2):
    s1, e1 = seg1
    s2, e2 = seg2
    
    inter = max(0, min(e1, e2) - max(s1, s2))
    
    len1 = e1 - s1
    len2 = e2 - s2
    
    return inter / min(len1, len2) if min(len1, len2) > 0 else 0

In [24]:
def temporal_NMS(timestamps, use_iou=True, threshold=0.5):
    """Apply temporal NMS to a list of timestamps."""
    keep = []
    
    segments = timestamps.copy()

    while segments:
        best = segments[0]
        keep.append(best)

        remaining = []

        for seg in segments[1:]:
            if use_iou:
                metric = temporal_iou(
                    best,
                    seg
                )
            else:
                metric = temporal_iom(
                    best,
                    seg
                )

            if metric < threshold:
                remaining.append(seg)

        segments = remaining

    return keep

In [25]:
retrieval_df["video_temporal_NMS_timestamps"] = retrieval_df.apply(lambda row: temporal_NMS(row["video_retrieval_timestamps"]), axis=1)
retrieval_df["audio_temporal_NMS_timestamps"] = retrieval_df.apply(lambda row: temporal_NMS(row["audio_retrieval_timestamps"]), axis=1)

In [26]:
retrieval_df["video_temporal_NMS_IoU"] = retrieval_df.apply(lambda row: compute_IoU(row["video_temporal_NMS_timestamps"], row["query_start_sec"], row["query_end_sec"]), axis=1)
retrieval_df["audio_temporal_NMS_IoU"] = retrieval_df.apply(lambda row: compute_IoU(row["audio_temporal_NMS_timestamps"], row["query_start_sec"], row["query_end_sec"]), axis=1)

In [27]:
retrieval_df["video_temporal_NMS_recall_at_3_0.3"] = retrieval_df["video_temporal_NMS_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.3, iou_list))
retrieval_df["audio_temporal_NMS_recall_at_3_0.3"] = retrieval_df["audio_temporal_NMS_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.3, iou_list))

retrieval_df["video_temporal_NMS_recall_at_3_0.5"] = retrieval_df["video_temporal_NMS_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.5, iou_list))
retrieval_df["audio_temporal_NMS_recall_at_3_0.5"] = retrieval_df["audio_temporal_NMS_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.5, iou_list))

retrieval_df["video_temporal_NMS_recall_at_5_0.3"] = retrieval_df["video_temporal_NMS_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.3, iou_list))
retrieval_df["audio_temporal_NMS_recall_at_5_0.3"] = retrieval_df["audio_temporal_NMS_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.3, iou_list))

retrieval_df["video_temporal_NMS_recall_at_5_0.5"] = retrieval_df["video_temporal_NMS_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.5, iou_list))
retrieval_df["audio_temporal_NMS_recall_at_5_0.5"] = retrieval_df["audio_temporal_NMS_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.5, iou_list))

In [28]:
retrieval_df["video_temporal_NMS_mean_IoU_top_3"] = (retrieval_df["video_temporal_NMS_recall_at_3_0.3"] + retrieval_df["video_temporal_NMS_recall_at_3_0.5"]) / 2
retrieval_df["audio_temporal_NMS_mean_IoU_top_3"] = (retrieval_df["audio_temporal_NMS_recall_at_3_0.3"] + retrieval_df["audio_temporal_NMS_recall_at_3_0.5"]) / 2

retrieval_df["video_temporal_NMS_mean_IoU_top_5"] = (retrieval_df["video_temporal_NMS_recall_at_5_0.3"] + retrieval_df["video_temporal_NMS_recall_at_5_0.5"]) / 2
retrieval_df["audio_temporal_NMS_mean_IoU_top_5"] = (retrieval_df["audio_temporal_NMS_recall_at_5_0.3"] + retrieval_df["audio_temporal_NMS_recall_at_5_0.5"]) / 2

### IoM-based NMS

In [29]:
retrieval_df["video_temporal_NMS_IoM_timestamps"] = retrieval_df.apply(lambda row: temporal_NMS(row["video_retrieval_timestamps"], use_iou=False, threshold=0.8), axis=1)
retrieval_df["audio_temporal_NMS_IoM_timestamps"] = retrieval_df.apply(lambda row: temporal_NMS(row["audio_retrieval_timestamps"], use_iou=False, threshold=0.8), axis=1)

In [30]:
retrieval_df["video_temporal_NMS_IoM_IoU"] = retrieval_df.apply(lambda row: compute_IoU(row["video_temporal_NMS_IoM_timestamps"], row["query_start_sec"], row["query_end_sec"]), axis=1)
retrieval_df["audio_temporal_NMS_IoM_IoU"] = retrieval_df.apply(lambda row: compute_IoU(row["audio_temporal_NMS_IoM_timestamps"], row["query_start_sec"], row["query_end_sec"]), axis=1)

In [31]:
retrieval_df["video_temporal_NMS_IoM_recall_at_3_0.3"] = retrieval_df["video_temporal_NMS_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.3, iou_list))
retrieval_df["audio_temporal_NMS_IoM_recall_at_3_0.3"] = retrieval_df["audio_temporal_NMS_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.3, iou_list))

retrieval_df["video_temporal_NMS_IoM_recall_at_3_0.5"] = retrieval_df["video_temporal_NMS_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.5, iou_list))
retrieval_df["audio_temporal_NMS_IoM_recall_at_3_0.5"] = retrieval_df["audio_temporal_NMS_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.5, iou_list))

retrieval_df["video_temporal_NMS_IoM_recall_at_5_0.3"] = retrieval_df["video_temporal_NMS_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.3, iou_list))
retrieval_df["audio_temporal_NMS_IoM_recall_at_5_0.3"] = retrieval_df["audio_temporal_NMS_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.3, iou_list))

retrieval_df["video_temporal_NMS_IoM_recall_at_5_0.5"] = retrieval_df["video_temporal_NMS_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.5, iou_list))
retrieval_df["audio_temporal_NMS_IoM_recall_at_5_0.5"] = retrieval_df["audio_temporal_NMS_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.5, iou_list))

In [32]:
retrieval_df["video_temporal_NMS_IoM_mean_IoU_top_3"] = (retrieval_df["video_temporal_NMS_IoM_recall_at_3_0.3"] + retrieval_df["video_temporal_NMS_IoM_recall_at_3_0.5"]) / 2
retrieval_df["audio_temporal_NMS_IoM_mean_IoU_top_3"] = (retrieval_df["audio_temporal_NMS_IoM_recall_at_3_0.3"] + retrieval_df["audio_temporal_NMS_IoM_recall_at_3_0.5"]) / 2

retrieval_df["video_temporal_NMS_IoM_mean_IoU_top_5"] = (retrieval_df["video_temporal_NMS_IoM_recall_at_5_0.3"] + retrieval_df["video_temporal_NMS_IoM_recall_at_5_0.5"]) / 2
retrieval_df["audio_temporal_NMS_IoM_mean_IoU_top_5"] = (retrieval_df["audio_temporal_NMS_IoM_recall_at_5_0.3"] + retrieval_df["audio_temporal_NMS_IoM_recall_at_5_0.5"]) / 2

### Soft Score NMS

In [33]:
# def adjusted_score(segment, raw_score, alpha):
#     start, end = segment
#     duration = end - start
#     return raw_score * (1 / duration) ** alpha

In [34]:
# def soft_score_soft_iom_nms(timestamps, scores, iom_threshold=0.8, alpha=0.5):
#     keep = []
        
#     segments = sorted(zip(timestamps, scores), key=lambda x: adjusted_score(x[0], x[1], alpha), reverse=True)

#     while segments:
#         best = segments[0]
#         keep.append(best)

#         remaining = []

#         for seg in segments[1:]:
#             metric = temporal_iom(best[0], seg[0])
            
#             if metric < iom_threshold:
#                 remaining.append(seg)

#         segments = remaining

#     return [seg for seg, score in keep]

In [35]:
import math

In [36]:
def soft_nms(segments, scores, iom_threshold=0.5, use_linear=True, use_iom=True, sigma=0.5, score_threshold=0.001):
    segments = list(zip(segments, scores))
    keep = []

    while segments:

        # Sort by current score
        segments.sort(key=lambda x: x[1], reverse=True)

        best_seg, best_score = segments[0]
        keep.append((best_seg, best_score))

        updated = []

        for seg, score in segments[1:]:

            overlap = temporal_iou(best_seg, seg) if not use_iom else temporal_iom(best_seg, seg)

            if use_linear:
                if overlap > iom_threshold:
                    score *= (1 - overlap)
            else:
                score *= math.exp(- (overlap ** 2) / sigma)
            
            if score > score_threshold:
                updated.append((seg, score))

        segments = updated

    return [seg for seg, _ in keep]

#### IoM + Linear

In [37]:
import ast

retrieval_df["qwen_distances"] = retrieval_df["qwen_distances"].apply(ast.literal_eval)
retrieval_df["clap_distances"] = retrieval_df["clap_distances"].apply(ast.literal_eval)

In [38]:
retrieval_df["video_temporal_soft_NMS_linear_IoM_timestamps"] = retrieval_df.apply(lambda row: soft_nms(row["video_retrieval_timestamps"], row["qwen_distances"]), axis=1)
retrieval_df["audio_temporal_soft_NMS_linear_IoM_timestamps"] = retrieval_df.apply(lambda row: soft_nms(row["audio_retrieval_timestamps"], row["clap_distances"]), axis=1)

In [39]:
retrieval_df["video_temporal_soft_NMS_linear_IoM_IoU"] = retrieval_df.apply(lambda row: compute_IoU(row["video_temporal_soft_NMS_linear_IoM_timestamps"], row["query_start_sec"], row["query_end_sec"]), axis=1)
retrieval_df["audio_temporal_soft_NMS_linear_IoM_IoU"] = retrieval_df.apply(lambda row: compute_IoU(row["audio_temporal_soft_NMS_linear_IoM_timestamps"], row["query_start_sec"], row["query_end_sec"]), axis=1)

In [40]:
retrieval_df["video_temporal_soft_NMS_linear_IoM_recall_at_3_0.3"] = retrieval_df["video_temporal_soft_NMS_linear_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.3, iou_list))
retrieval_df["audio_temporal_soft_NMS_linear_IoM_recall_at_3_0.3"] = retrieval_df["audio_temporal_soft_NMS_linear_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.3, iou_list))

retrieval_df["video_temporal_soft_NMS_linear_IoM_recall_at_3_0.5"] = retrieval_df["video_temporal_soft_NMS_linear_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.5, iou_list))
retrieval_df["audio_temporal_soft_NMS_linear_IoM_recall_at_3_0.5"] = retrieval_df["audio_temporal_soft_NMS_linear_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.5, iou_list))

retrieval_df["video_temporal_soft_NMS_linear_IoM_recall_at_5_0.3"] = retrieval_df["video_temporal_soft_NMS_linear_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.3, iou_list))
retrieval_df["audio_temporal_soft_NMS_linear_IoM_recall_at_5_0.3"] = retrieval_df["audio_temporal_soft_NMS_linear_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.3, iou_list))

retrieval_df["video_temporal_soft_NMS_linear_IoM_recall_at_5_0.5"] = retrieval_df["video_temporal_soft_NMS_linear_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.5, iou_list))
retrieval_df["audio_temporal_soft_NMS_linear_IoM_recall_at_5_0.5"] = retrieval_df["audio_temporal_soft_NMS_linear_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.5, iou_list))

In [41]:
retrieval_df["video_temporal_soft_NMS_linear_IoM_mean_IoU_top_3"] = (retrieval_df["video_temporal_soft_NMS_linear_IoM_recall_at_3_0.3"] + retrieval_df["video_temporal_soft_NMS_linear_IoM_recall_at_3_0.5"]) / 2
retrieval_df["audio_temporal_soft_NMS_linear_IoM_mean_IoU_top_3"] = (retrieval_df["audio_temporal_soft_NMS_linear_IoM_recall_at_3_0.3"] + retrieval_df["audio_temporal_soft_NMS_linear_IoM_recall_at_3_0.5"]) / 2

retrieval_df["video_temporal_soft_NMS_linear_IoM_mean_IoU_top_5"] = (retrieval_df["video_temporal_soft_NMS_linear_IoM_recall_at_5_0.3"] + retrieval_df["video_temporal_soft_NMS_linear_IoM_recall_at_5_0.5"]) / 2
retrieval_df["audio_temporal_soft_NMS_linear_IoM_mean_IoU_top_5"] = (retrieval_df["audio_temporal_soft_NMS_linear_IoM_recall_at_5_0.3"] + retrieval_df["audio_temporal_soft_NMS_linear_IoM_recall_at_5_0.5"]) / 2

#### IoM + Gaussian

In [42]:
retrieval_df["video_temporal_soft_NMS_gaussian_IoM_timestamps"] = retrieval_df.apply(lambda row: soft_nms(row["video_retrieval_timestamps"], row["qwen_distances"], use_linear=False), axis=1)
retrieval_df["audio_temporal_soft_NMS_gaussian_IoM_timestamps"] = retrieval_df.apply(lambda row: soft_nms(row["audio_retrieval_timestamps"], row["clap_distances"], use_linear=False), axis=1)

In [43]:
retrieval_df["video_temporal_soft_NMS_gaussian_IoM_IoU"] = retrieval_df.apply(lambda row: compute_IoU(row["video_temporal_soft_NMS_gaussian_IoM_timestamps"], row["query_start_sec"], row["query_end_sec"]), axis=1)
retrieval_df["audio_temporal_soft_NMS_gaussian_IoM_IoU"] = retrieval_df.apply(lambda row: compute_IoU(row["audio_temporal_soft_NMS_gaussian_IoM_timestamps"], row["query_start_sec"], row["query_end_sec"]), axis=1)

In [44]:
retrieval_df["video_temporal_soft_NMS_gaussian_IoM_recall_at_3_0.3"] = retrieval_df["video_temporal_soft_NMS_gaussian_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.3, iou_list))
retrieval_df["audio_temporal_soft_NMS_gaussian_IoM_recall_at_3_0.3"] = retrieval_df["audio_temporal_soft_NMS_gaussian_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.3, iou_list))

retrieval_df["video_temporal_soft_NMS_gaussian_IoM_recall_at_3_0.5"] = retrieval_df["video_temporal_soft_NMS_gaussian_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.5, iou_list))
retrieval_df["audio_temporal_soft_NMS_gaussian_IoM_recall_at_3_0.5"] = retrieval_df["audio_temporal_soft_NMS_gaussian_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.5, iou_list))

retrieval_df["video_temporal_soft_NMS_gaussian_IoM_recall_at_5_0.3"] = retrieval_df["video_temporal_soft_NMS_gaussian_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.3, iou_list))
retrieval_df["audio_temporal_soft_NMS_gaussian_IoM_recall_at_5_0.3"] = retrieval_df["audio_temporal_soft_NMS_gaussian_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.3, iou_list))

retrieval_df["video_temporal_soft_NMS_gaussian_IoM_recall_at_5_0.5"] = retrieval_df["video_temporal_soft_NMS_gaussian_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.5, iou_list))
retrieval_df["audio_temporal_soft_NMS_gaussian_IoM_recall_at_5_0.5"] = retrieval_df["audio_temporal_soft_NMS_gaussian_IoM_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.5, iou_list))

In [45]:
retrieval_df["video_temporal_soft_NMS_gaussian_IoM_mean_IoU_top_3"] = (retrieval_df["video_temporal_soft_NMS_gaussian_IoM_recall_at_3_0.3"] + retrieval_df["video_temporal_soft_NMS_gaussian_IoM_recall_at_3_0.5"]) / 2
retrieval_df["audio_temporal_soft_NMS_gaussian_IoM_mean_IoU_top_3"] = (retrieval_df["audio_temporal_soft_NMS_gaussian_IoM_recall_at_3_0.3"] + retrieval_df["audio_temporal_soft_NMS_gaussian_IoM_recall_at_3_0.5"]) / 2

retrieval_df["video_temporal_soft_NMS_gaussian_IoM_mean_IoU_top_5"] = (retrieval_df["video_temporal_soft_NMS_gaussian_IoM_recall_at_5_0.3"] + retrieval_df["video_temporal_soft_NMS_gaussian_IoM_recall_at_5_0.5"]) / 2
retrieval_df["audio_temporal_soft_NMS_gaussian_IoM_mean_IoU_top_5"] = (retrieval_df["audio_temporal_soft_NMS_gaussian_IoM_recall_at_5_0.3"] + retrieval_df["audio_temporal_soft_NMS_gaussian_IoM_recall_at_5_0.5"]) / 2

#### IoU + Linear

In [46]:
retrieval_df["video_temporal_soft_NMS_linear_IoU_timestamps"] = retrieval_df.apply(lambda row: soft_nms(row["video_retrieval_timestamps"], row["qwen_distances"], use_iom=False), axis=1)
retrieval_df["audio_temporal_soft_NMS_linear_IoU_timestamps"] = retrieval_df.apply(lambda row: soft_nms(row["audio_retrieval_timestamps"], row["clap_distances"], use_iom=False), axis=1)

In [47]:
retrieval_df["video_temporal_soft_NMS_linear_IoU_IoU"] = retrieval_df.apply(lambda row: compute_IoU(row["video_temporal_soft_NMS_linear_IoU_timestamps"], row["query_start_sec"], row["query_end_sec"]), axis=1)
retrieval_df["audio_temporal_soft_NMS_linear_IoU_IoU"] = retrieval_df.apply(lambda row: compute_IoU(row["audio_temporal_soft_NMS_linear_IoU_timestamps"], row["query_start_sec"], row["query_end_sec"]), axis=1)

In [48]:
retrieval_df["video_temporal_soft_NMS_linear_IoU_recall_at_3_0.3"] = retrieval_df["video_temporal_soft_NMS_linear_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.3, iou_list))
retrieval_df["audio_temporal_soft_NMS_linear_IoU_recall_at_3_0.3"] = retrieval_df["audio_temporal_soft_NMS_linear_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.3, iou_list))

retrieval_df["video_temporal_soft_NMS_linear_IoU_recall_at_3_0.5"] = retrieval_df["video_temporal_soft_NMS_linear_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.5, iou_list))
retrieval_df["audio_temporal_soft_NMS_linear_IoU_recall_at_3_0.5"] = retrieval_df["audio_temporal_soft_NMS_linear_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.5, iou_list))

retrieval_df["video_temporal_soft_NMS_linear_IoU_recall_at_5_0.3"] = retrieval_df["video_temporal_soft_NMS_linear_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.3, iou_list))
retrieval_df["audio_temporal_soft_NMS_linear_IoU_recall_at_5_0.3"] = retrieval_df["audio_temporal_soft_NMS_linear_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.3, iou_list))

retrieval_df["video_temporal_soft_NMS_linear_IoU_recall_at_5_0.5"] = retrieval_df["video_temporal_soft_NMS_linear_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.5, iou_list))
retrieval_df["audio_temporal_soft_NMS_linear_IoU_recall_at_5_0.5"] = retrieval_df["audio_temporal_soft_NMS_linear_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.5, iou_list))

In [49]:
retrieval_df["video_temporal_soft_NMS_linear_IoU_mean_IoU_top_3"] = (retrieval_df["video_temporal_soft_NMS_linear_IoU_recall_at_3_0.3"] + retrieval_df["video_temporal_soft_NMS_linear_IoU_recall_at_3_0.5"]) / 2
retrieval_df["audio_temporal_soft_NMS_linear_IoU_mean_IoU_top_3"] = (retrieval_df["audio_temporal_soft_NMS_linear_IoU_recall_at_3_0.3"] + retrieval_df["audio_temporal_soft_NMS_linear_IoU_recall_at_3_0.5"]) / 2

retrieval_df["video_temporal_soft_NMS_linear_IoU_mean_IoU_top_5"] = (retrieval_df["video_temporal_soft_NMS_linear_IoU_recall_at_5_0.3"] + retrieval_df["video_temporal_soft_NMS_linear_IoU_recall_at_5_0.5"]) / 2
retrieval_df["audio_temporal_soft_NMS_linear_IoU_mean_IoU_top_5"] = (retrieval_df["audio_temporal_soft_NMS_linear_IoU_recall_at_5_0.3"] + retrieval_df["audio_temporal_soft_NMS_linear_IoU_recall_at_5_0.5"]) / 2

/tmp/ipykernel_4159998/1598645864.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["audio_temporal_soft_NMS_linear_IoU_mean_IoU_top_3"] = (retrieval_df["audio_temporal_soft_NMS_linear_IoU_recall_at_3_0.3"] + retrieval_df["audio_temporal_soft_NMS_linear_IoU_recall_at_3_0.5"]) / 2
/tmp/ipykernel_4159998/1598645864.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["video_temporal_soft_NMS_linear_IoU_mean_IoU_top_5"] = (retrieval_df["video_temporal_soft_NMS_linear_IoU_recall_at_5_0.3"] + retrieval_df["video_temporal_soft_NMS_linear_IoU_recall_at_5_0.5"]) / 2
/tmp/ipykernel_4159998/1598645864.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["audio_temporal_soft_NMS_linear_IoU_mean_IoU_top_5"] = (retrieval_df["audio_temporal_soft_NMS_linear_IoU_recall_at_5_0.3"] + retrieval_df["audio_temporal_soft_NMS_linear_IoU_recall_at_5_0.5"]) / 2

#### IoU + Gaussian

In [50]:
retrieval_df["video_temporal_soft_NMS_gaussian_IoU_timestamps"] = retrieval_df.apply(lambda row: soft_nms(row["video_retrieval_timestamps"], row["qwen_distances"], use_iom=False, use_linear=False), axis=1)
retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_timestamps"] = retrieval_df.apply(lambda row: soft_nms(row["audio_retrieval_timestamps"], row["clap_distances"], use_iom=False, use_linear=False), axis=1)

/tmp/ipykernel_4159998/629961678.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["video_temporal_soft_NMS_gaussian_IoU_timestamps"] = retrieval_df.apply(lambda row: soft_nms(row["video_retrieval_timestamps"], row["qwen_distances"], use_iom=False, use_linear=False), axis=1)
/tmp/ipykernel_4159998/629961678.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_timestamps"] = retrieval_df.apply(lambda row: soft_nms(row["audio_retrieval_timestamps"], row["clap_distances"], use_iom=False, use_linear=False), axis=1)

In [51]:
retrieval_df["video_temporal_soft_NMS_gaussian_IoU_IoU"] = retrieval_df.apply(lambda row: compute_IoU(row["video_temporal_soft_NMS_gaussian_IoU_timestamps"], row["query_start_sec"], row["query_end_sec"]), axis=1)
retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_IoU"] = retrieval_df.apply(lambda row: compute_IoU(row["audio_temporal_soft_NMS_gaussian_IoU_timestamps"], row["query_start_sec"], row["query_end_sec"]), axis=1)

/tmp/ipykernel_4159998/2144657274.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["video_temporal_soft_NMS_gaussian_IoU_IoU"] = retrieval_df.apply(lambda row: compute_IoU(row["video_temporal_soft_NMS_gaussian_IoU_timestamps"], row["query_start_sec"], row["query_end_sec"]), axis=1)
/tmp/ipykernel_4159998/2144657274.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_IoU"] = retrieval_df.apply(lambda row: compute_IoU(row["audio_temporal_soft_NMS_gaussian_IoU_timestamps"], row["query_start_sec"], row["query_end_sec"]), axis=1)

In [52]:
retrieval_df["video_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.3"] = retrieval_df["video_temporal_soft_NMS_gaussian_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.3, iou_list))
retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.3"] = retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.3, iou_list))

retrieval_df["video_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.5"] = retrieval_df["video_temporal_soft_NMS_gaussian_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.5, iou_list))
retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.5"] = retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.5, iou_list))

retrieval_df["video_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.3"] = retrieval_df["video_temporal_soft_NMS_gaussian_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.3, iou_list))
retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.3"] = retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.3, iou_list))

retrieval_df["video_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.5"] = retrieval_df["video_temporal_soft_NMS_gaussian_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.5, iou_list))
retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.5"] = retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.5, iou_list))

/tmp/ipykernel_4159998/3426281907.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["video_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.3"] = retrieval_df["video_temporal_soft_NMS_gaussian_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.3, iou_list))
/tmp/ipykernel_4159998/3426281907.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.3"] = retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.3, iou_list))
/tmp/ipykernel_4159998/3426281907.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["video_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.5"] = retrieval_df["video_temporal_soft_NMS_gaussian_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.5, iou_list))
/tmp/ipykernel_4159998/3426281907.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.5"] = retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(3, 0.5, iou_list))
/tmp/ipykernel_4159998/3426281907.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["video_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.3"] = retrieval_df["video_temporal_soft_NMS_gaussian_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.3, iou_list))
/tmp/ipykernel_4159998/3426281907.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.3"] = retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.3, iou_list))
/tmp/ipykernel_4159998/3426281907.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["video_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.5"] = retrieval_df["video_temporal_soft_NMS_gaussian_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.5, iou_list))
/tmp/ipykernel_4159998/3426281907.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.5"] = retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_IoU"].apply(lambda iou_list: compute_recall_at_k(5, 0.5, iou_list))

In [53]:
retrieval_df["video_temporal_soft_NMS_gaussian_IoU_mean_IoU_top_3"] = (retrieval_df["video_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.3"] + retrieval_df["video_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.5"]) / 2
retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_mean_IoU_top_3"] = (retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.3"] + retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.5"]) / 2

retrieval_df["video_temporal_soft_NMS_gaussian_IoU_mean_IoU_top_5"] = (retrieval_df["video_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.3"] + retrieval_df["video_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.5"]) / 2
retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_mean_IoU_top_5"] = (retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.3"] + retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.5"]) / 2

/tmp/ipykernel_4159998/1069943688.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["video_temporal_soft_NMS_gaussian_IoU_mean_IoU_top_3"] = (retrieval_df["video_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.3"] + retrieval_df["video_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.5"]) / 2
/tmp/ipykernel_4159998/1069943688.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_mean_IoU_top_3"] = (retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.3"] + retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.5"]) / 2
/tmp/ipykernel_4159998/1069943688.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["video_temporal_soft_NMS_gaussian_IoU_mean_IoU_top_5"] = (retrieval_df["video_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.3"] + retrieval_df["video_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.5"]) / 2
/tmp/ipykernel_4159998/1069943688.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_mean_IoU_top_5"] = (retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.3"] + retrieval_df["audio_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.5"]) / 2

### Results

In [54]:
cols = [
            "video_IoU_recall_at_3_0.3", "audio_IoU_recall_at_3_0.3",
              "video_IoU_recall_at_3_0.5", "audio_IoU_recall_at_3_0.5",
              "video_IoU_recall_at_5_0.3", "audio_IoU_recall_at_5_0.3",
              "video_IoU_recall_at_5_0.5", "audio_IoU_recall_at_5_0.5",
              
             "video_temporal_NMS_recall_at_3_0.3", "audio_temporal_NMS_recall_at_3_0.3", 
              "video_temporal_NMS_recall_at_3_0.5", "audio_temporal_NMS_recall_at_3_0.5",
              "video_temporal_NMS_recall_at_5_0.3", "audio_temporal_NMS_recall_at_5_0.3",
              "video_temporal_NMS_recall_at_5_0.5", "audio_temporal_NMS_recall_at_5_0.5",
              
              "video_temporal_NMS_IoM_recall_at_3_0.3", "audio_temporal_NMS_IoM_recall_at_3_0.3",
              "video_temporal_NMS_IoM_recall_at_3_0.5", "audio_temporal_NMS_IoM_recall_at_3_0.5",
              "video_temporal_NMS_IoM_recall_at_5_0.3", "audio_temporal_NMS_IoM_recall_at_5_0.3",
              "video_temporal_NMS_IoM_recall_at_5_0.5", "audio_temporal_NMS_IoM_recall_at_5_0.5",
              
              "video_temporal_soft_NMS_linear_IoM_recall_at_3_0.3", "audio_temporal_soft_NMS_linear_IoM_recall_at_3_0.3",
                "video_temporal_soft_NMS_linear_IoM_recall_at_3_0.5", "audio_temporal_soft_NMS_linear_IoM_recall_at_3_0.5",
                "video_temporal_soft_NMS_linear_IoM_recall_at_5_0.3", "audio_temporal_soft_NMS_linear_IoM_recall_at_5_0.3",
                "video_temporal_soft_NMS_linear_IoM_recall_at_5_0.5", "audio_temporal_soft_NMS_linear_IoM_recall_at_5_0.5",
                
                "video_temporal_soft_NMS_gaussian_IoM_recall_at_3_0.3", "audio_temporal_soft_NMS_gaussian_IoM_recall_at_3_0.3",
                "video_temporal_soft_NMS_gaussian_IoM_recall_at_3_0.5", "audio_temporal_soft_NMS_gaussian_IoM_recall_at_3_0.5",
                "video_temporal_soft_NMS_gaussian_IoM_recall_at_5_0.3", "audio_temporal_soft_NMS_gaussian_IoM_recall_at_5_0.3",
                "video_temporal_soft_NMS_gaussian_IoM_recall_at_5_0.5", "audio_temporal_soft_NMS_gaussian_IoM_recall_at_5_0.5",
                
                "video_temporal_soft_NMS_linear_IoU_recall_at_3_0.3", "audio_temporal_soft_NMS_linear_IoU_recall_at_3_0.3",
                "video_temporal_soft_NMS_linear_IoU_recall_at_3_0.5", "audio_temporal_soft_NMS_linear_IoU_recall_at_3_0.5",
                "video_temporal_soft_NMS_linear_IoU_recall_at_5_0.3", "audio_temporal_soft_NMS_linear_IoU_recall_at_5_0.3",
                "video_temporal_soft_NMS_linear_IoU_recall_at_5_0.5", "audio_temporal_soft_NMS_linear_IoU_recall_at_5_0.5",
                
                "video_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.3", "audio_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.3",
                "video_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.5", "audio_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.5",
                "video_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.3", "audio_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.3",
                "video_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.5", "audio_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.5"
    
    ]

In [55]:
retrieval_df[cols].describe()

,video_IoU_recall_at_3_0.3,audio_IoU_recall_at_3_0.3,video_IoU_recall_at_3_0.5,audio_IoU_recall_at_3_0.5,video_IoU_recall_at_5_0.3,audio_IoU_recall_at_5_0.3,video_IoU_recall_at_5_0.5,audio_IoU_recall_at_5_0.5,video_temporal_NMS_recall_at_3_0.3,audio_temporal_NMS_recall_at_3_0.3,...,video_temporal_soft_NMS_linear_IoU_recall_at_5_0.5,audio_temporal_soft_NMS_linear_IoU_recall_at_5_0.5,video_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.3,audio_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.3,video_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.5,audio_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.5,video_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.3,audio_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.3,video_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.5,audio_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.5
count,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,55.000000,...,55.000000,55.000000,55.000000,55.000000,55.0,55.000000,55.000000,55.000000,55.000000,55.000000
mean,0.036364,0.072727,0.018182,0.018182,0.054545,0.072727,0.018182,0.018182,0.054545,0.109091,...,0.018182,0.036364,0.036364,0.109091,0.0,0.036364,0.054545,0.127273,0.018182,0.054545
std,0.188919,0.262082,0.134840,0.134840,0.229184,0.262082,0.134840,0.134840,0.229184,0.314627,...,0.134840,0.188919,0.188919,0.314627,0.0,0.188919,0.229184,0.336350,0.134840,0.229184
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000

In [56]:
means = retrieval_df[cols].mean().sort_values(ascending=False)

for col, avg in means.items():
    print(f"{col}: {avg:.4f}")

audio_temporal_NMS_IoM_recall_at_5_0.3: 0.1273
audio_temporal_soft_NMS_gaussian_IoM_recall_at_5_0.3: 0.1273
audio_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.3: 0.1273
audio_temporal_NMS_recall_at_5_0.3: 0.1091
audio_temporal_soft_NMS_linear_IoM_recall_at_3_0.3: 0.1091
audio_temporal_soft_NMS_gaussian_IoM_recall_at_3_0.3: 0.1091
audio_temporal_NMS_recall_at_3_0.3: 0.1091
audio_temporal_NMS_IoM_recall_at_3_0.3: 0.1091
audio_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.3: 0.1091
audio_temporal_soft_NMS_linear_IoM_recall_at_5_0.3: 0.1091
audio_temporal_soft_NMS_linear_IoU_recall_at_5_0.3: 0.1091
audio_temporal_soft_NMS_linear_IoU_recall_at_3_0.3: 0.0909
audio_IoU_recall_at_3_0.3: 0.0727
audio_IoU_recall_at_5_0.3: 0.0727
video_temporal_NMS_recall_at_5_0.3: 0.0727
video_temporal_soft_NMS_linear_IoU_recall_at_5_0.3: 0.0727
video_temporal_NMS_recall_at_3_0.3: 0.0545
video_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.3: 0.0545
video_temporal_soft_NMS_gaussian_IoM_recall_at_5_0.3: 0.0545
audio_temporal_soft_NMS_gaussian_IoM_recall_at_5_0.5: 0.0545
audio_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.5: 0.0545
video_IoU_recall_at_5_0.3: 0.0545
video_temporal_soft_NMS_linear_IoU_recall_at_3_0.3: 0.0545
audio_temporal_NMS_IoM_recall_at_5_0.5: 0.0364
video_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.3: 0.0364
audio_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.5: 0.0364
audio_temporal_soft_NMS_linear_IoU_recall_at_3_0.5: 0.0364
audio_temporal_soft_NMS_linear_IoU_recall_at_5_0.5: 0.0364
audio_temporal_soft_NMS_linear_IoM_recall_at_5_0.5: 0.0364
video_temporal_soft_NMS_linear_IoM_recall_at_5_0.3: 0.0364
audio_temporal_soft_NMS_gaussian_IoM_recall_at_3_0.5: 0.0364
video_temporal_NMS_IoM_recall_at_5_0.3: 0.0364
audio_temporal_NMS_recall_at_3_0.5: 0.0364
video_temporal_NMS_recall_at_5_0.5: 0.0364
audio_temporal_NMS_recall_at_5_0.5: 0.0364
video_IoU_recall_at_3_0.3: 0.0364
video_temporal_NMS_IoM_recall_at_3_0.3: 0.0364
audio_temporal_NMS_IoM_recall_at_3_0.5: 0.0364
audio_temporal_soft_NMS_linear_IoM_recall_at_3_0.5: 0.0364
video_temporal_soft_NMS_linear_IoM_recall_at_3_0.3: 0.0364
video_temporal_soft_NMS_gaussian_IoM_recall_at_3_0.3: 0.0364
video_temporal_soft_NMS_linear_IoU_recall_at_5_0.5: 0.0182
video_temporal_NMS_recall_at_3_0.5: 0.0182
video_temporal_soft_NMS_linear_IoU_recall_at_3_0.5: 0.0182
audio_IoU_recall_at_3_0.5: 0.0182
video_IoU_recall_at_3_0.5: 0.0182
video_IoU_recall_at_5_0.5: 0.0182
audio_IoU_recall_at_5_0.5: 0.0182
video_temporal_soft_NMS_gaussian_IoU_recall_at_5_0.5: 0.0182
video_temporal_soft_NMS_gaussian_IoM_recall_at_5_0.5: 0.0182
video_temporal_NMS_IoM_recall_at_5_0.5: 0.0000
video_temporal_NMS_IoM_recall_at_3_0.5: 0.0000
video_temporal_soft_NMS_gaussian_IoM_recall_at_3_0.5: 0.0000
video_temporal_soft_NMS_linear_IoM_recall_at_5_0.5: 0.0000
video_temporal_soft_NMS_linear_IoM_recall_at_3_0.5: 0.0000
video_temporal_soft_NMS_gaussian_IoU_recall_at_3_0.5: 0.0000

### Maximum Possible IoU given the segments

In [57]:
def get_max_IoU(iou_list):
    """Get the maximum IoU from a list of IoU values."""
    return max(iou_list).item()

In [58]:
retrieval_df["max_IoU"] = retrieval_df["video_IoU"].apply(get_max_IoU)

/tmp/ipykernel_4159998/3143952259.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["max_IoU"] = retrieval_df["video_IoU"].apply(get_max_IoU)

In [59]:
retrieval_df["max_IoU_recall_0.5"] = retrieval_df["max_IoU"] >= 0.5
retrieval_df["max_IoU_recall_0.3"] = retrieval_df["max_IoU"] >= 0.3

/tmp/ipykernel_4159998/826970278.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["max_IoU_recall_0.5"] = retrieval_df["max_IoU"] >= 0.5
/tmp/ipykernel_4159998/826970278.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  retrieval_df["max_IoU_recall_0.3"] = retrieval_df["max_IoU"] >= 0.3

In [60]:
print("Max IoU recall at 0.5:", retrieval_df["max_IoU_recall_0.5"].mean())
print("Max IoU recall at 0.3:", retrieval_df["max_IoU_recall_0.3"].mean())

Max IoU recall at 0.5: 0.8363636363636363
Max IoU recall at 0.3: 0.9090909090909091

In [61]:
ceiling_loss_0point_5 = 1 - retrieval_df["max_IoU_recall_0.5"].mean()
ceiling_loss_0point_3 = 1 - retrieval_df["max_IoU_recall_0.3"].mean()

In [62]:
print(f"Ceiling loss at IoU 0.5: {ceiling_loss_0point_5:.4f}")
print(f"Ceiling loss at IoU 0.3: {ceiling_loss_0point_3:.4f}")

Ceiling loss at IoU 0.5: 0.1636
Ceiling loss at IoU 0.3: 0.0909

In [63]:
ranking_loss_0point_5 = retrieval_df["max_IoU_recall_0.5"].mean() - retrieval_df["audio_temporal_NMS_IoM_recall_at_5_0.3"].mean()
ranking_loss_0point_3 = retrieval_df["max_IoU_recall_0.3"].mean() - retrieval_df["audio_temporal_NMS_IoM_recall_at_5_0.3"].mean()

In [64]:
print(f"Ranking loss at IoU 0.5: {ranking_loss_0point_5:.4f}")
print(f"Ranking loss at IoU 0.3: {ranking_loss_0point_3:.4f}")

Ranking loss at IoU 0.5: 0.7091
Ranking loss at IoU 0.3: 0.7818

In [66]:
retrieval_df.to_csv("/scratch/yag1/ego4d_data/v2/baseline_qwen_results.csv", index=False)